### ISSUE TITLE
Agenda for September 2020 Cross Pollination

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#11]
Re: https://github.com/nih-cfde/deliverables/issues/96

**Comment by ACharbonneau** [comment]
We are planning a more distributed, online event. Working on a poll to send to attendees that covers potential topics and days.

**Comment by ACharbonneau** [comment]
Survey sent 8/12

**Comment by ACharbonneau** [comment]
https://docs.google.com/spreadsheets/d/1WM4LbQ8ctki3ui7h9KTBZUXTIy9p3HhXk5a7yaQVU5c/edit#gid=1089477257

**Comment by marisalim** [comment]
CP is happening now! can this be closed?
