### ISSUE TITLE
Add information on reusing key pairs

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#124]
https://cfde-training-and-engagement.readthedocs-hosted.com/en/latest/Bioinformatics-Tutorials/GWAS-in-the-Cloud/aws_instance_setup/

Users should *not* be creating new key pairs every time they do something in amazon. They're re-useable. So, the instructions should say something like "if you already have a key pair" and "if you don't have a key pair" and have instructions for both

**Comment by abhijna** [comment]
#129
