### ISSUE TITLE
Streamline save locations and workflow

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#125]
In download the data, you have us download to our desktops and upload to AWS in a way that is going to be super error-prone:
$ scp -i /Desktop/amazon.pem path/to/file/pruned_coatColor_maf_geno.vcf.gz ubuntu@ec2-???-???-???-???.compute-1.amazonaws.com:/GWAS/.
$ gunzip pruned_coatColor_maf_geno.vcf.gz #unzip the vcf.
$ scp -i /Desktop/amazon.pem path/to/file/coatColor.pheno ubuntu@ec2-???-???-???-???.compute-1.amazonaws.com:/GWAS/.

It would be much simpler if in this section you re-structured to have the user do something like:

make a folder for this lesson locally
download the pem
move the pem to that folder
cd to that folder
chmod the pem
download the data files they need now, while you have them in the right place
then log into AWS (using the command you described, and point out that if they have trouble, they find in a copy/paste in 'Connect'
then do a very simple thing in AWS: ls and show them nothing is there
then type exit
NOW have them upload the data, the command is generic because they are already in the folder with the pem and the data
log back into AWS (it's good to do it multiple times, so they learn the ssh)
ls again. LOOK THERE'S STUFF NOW
then move on to installs
This does a few things:

It gives them a chance to practice logging in and out of AWS
It demonstrates that logging in and out does not kill the computer, so they understand that they are still paying for it
It gives a feeling of accomplishment. Something demonstrably happened, and it happened early in the lesson. They learned to move stuff to the cloud. Early wins keep learners motivated,
It reduce the number of things your user needs to keep in their head all at once to participate. In the current set up, your asking them to understand that theres a cloud and a local, and what is in each, and to keep track of a whole bunch of unfamiliar files (pems, data they don't know, software) spread across those two locations, and across different places in those locations. Giving them ONE folder locally to work in and ONE folder on the cloud to work in will free up the mental cycles they need to follow along with the actual science part.

On https://cfde-training-and-engagement.readthedocs-hosted.com/en/latest/Bioinformatics-Tutorials/GWAS-in-the-Cloud/aws_instance_setup/

The instructions you have do say 'save the pem to your desktop', but it's buried in a paragraph under an image instead of being a step. When a mac user (which is your expected user) hits "Download Key Pair" it is automatically downloaded to "Downloads" by default. If you're expecting the user to move it, that should be it's own step. I completely missed it.

**Comment by abhijna** [comment]
#129
