### ISSUE TITLE
Make warning more specific and add a tip box for how to recover

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#126]
https://cfde-training-and-engagement.readthedocs-hosted.com/en/latest/Bioinformatics-Tutorials/GWAS-in-the-Cloud/aws_instance_setup/

Last line is "You have now successfully launched your AWS instance. DO NOT CLOSE THIS PAGE YET." I honestly don't now which page is "THIS PAGE". The tutorial? The AWS management page? I would make this less yelly, and more tell me what I actually need (and how to get back to it if I misunderstood and did close it)

**Comment by abhijna** [comment]
#129
