### ISSUE TITLE
Oct 15 Training Site Release

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#141]

**Comment by s-canchi** [comment]
Use this issue to track all new additions, changes made to latest that will be merged into stable prior to Oct 15th release.
- @abhijna merged edits to the general GWAS tutorial that included:
      - combining setup and download data steps to maintain consistency of workspace
      - Fixed broken links
- Marisa updated Snakemake tutorial: text/step formats, add input/output with javascript tabs, edit hyperlinks that say 'here', move cheatsheets to separate Resources tab

**Comment by ACharbonneau** [comment]
So one vaguely annoying thing is that zenhub doesn't appear to connect issues I've added to this epic to this issue. So, if ya'll aren't going to use zenhub, I'll have to connect it both places. That's fine, just an observation. 

My view of this issue in zenhub looks like: ![image.png](https://images.zenhubusercontent.com/5f204fe0edbda0e7bf258e28/a95e60ab-cc68-4b15-bd22-f5ea9c051365)

**Comment by s-canchi** [comment]
@s-canchi PR merge includes:
- MIME type tutorial listed under CF tutorial header
- Integrated asciinema player such that the screencasts can now be local and the appearance is modifiable 
- PR template

**Comment by s-canchi** [comment]
@s-canchi added auto reviewer assignment workflow - This will assign two reviewers for merge into `latest` and currently set for the whole team approval for merge into `stable`
Also included auto release notes tracking workflow.

**Comment by ACharbonneau** [comment]
@nih-cfde/training  You might find your life to be somewhat improved if you look at my view of the repo, which you can get by installing a browser plugin: https://www.zenhub.com/extension

Example:

![image](https://user-images.githubusercontent.com/1719360/92532618-a75b7f00-f1fe-11ea-89ce-37ce2fdcc0bd.png)

**Comment by s-canchi** [comment]
Is there a way to use this on safari ? Could not find the extension or an app for it.

**Comment by ACharbonneau** [comment]
this is a duplicate of https://github.com/nih-cfde/deliverables/issues/89 closing
