### ISSUE TITLE
Site Visit A2CPS

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#17]
- Reached out 2-20-20: Visit should happen at TACC

**Comment by ACharbonneau** [comment]
Lora reached out to their PO. We think they're not responding due to pandemic issues, but PO did not have much insight. Need to regroup and start contacting other DCCs

**Comment by ACharbonneau** [comment]
@kutkatl heard from Ari. I've responded to that email looking for dates. Will follow up in ~a week if I haven't heard back

**Comment by ACharbonneau** [comment]
We are in the middle of choosing dates/times. Should have one by the end of the week. @josesanchez1815 is scheduling

**Comment by josesanchez1815** [comment]
# Orientation Meeting
**_June 12th, 2020 8AM - 11AM_** via Zoom Meetings
Owen White 
Titus Brown
Ari Khan
Martin Lindquist
James Carson
Amanda Charbonneau

**Comment by ctb** [comment]
is this EST or PST?

**Comment by ctb** [comment]
Ahh! I see from the e-mail it's PDT.

**Comment by ACharbonneau** [comment]
wait. That wasn't even an option in the poll??

**Comment by ACharbonneau** [comment]
@josesanchez1815 where did 8-11 come from?

**Comment by ACharbonneau** [comment]
Super weird. What time zone does doodle say you are in? 

mine says:
![image](https://user-images.githubusercontent.com/1719360/83537809-0fdde600-a4c3-11ea-8dd3-4189c08594f2.png)
for eastern time. But that should make yours 7am.

**Comment by ACharbonneau** [comment]
I wonder if theres a daylight savings issue

**Comment by josesanchez1815** [comment]
The Doodle says LA TIme for me

**Comment by josesanchez1815** [comment]
Ok, well it looks like I will have to double check these times with @ACharbonneau  as well if we use doodle like this in the future.

**Comment by ACharbonneau** [comment]
OK, I think I figured out the problem. It was putting in *my* timezone wrong. It had me in GMT-5 instead of GTM-4...they're both EST, just depends on whether you day light savings or not. That is SUPER annoying. The good news is that I can do the later time that day, so I'm fine with the invite you sent. Could you message @owhite and double check that he can make it though? that was outside his time range.

**Comment by josesanchez1815** [comment]
@ACharbonneau  Owen confirmed he is available 8am-11am PST (11am-2pm EST).

**Comment by ACharbonneau** [comment]
yay!

**Comment by jeremywalter** [comment]
Are we adding more info here, or is this issue complete?

**Comment by ACharbonneau** [comment]
Visit complete. Report underway
