### ISSUE TITLE
out of band globus group creation

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#176]
We need to register identities for PIs from the DCCs so they can actually use the report view in Epic 1. We're doing this off line rather than as a strict requirement of the epic, and will build a proper registration process later

- [ ] get together emails to request IDs from
- [ ] make sure I have them send the registration to the right place (Lee will tell me where)
- [ ] some kind of button clicking in globus to create the groups

**Comment by ACharbonneau** [comment]
added real words from #179 

> To track and manage the authorized reviewers for each DCC, we will create a Globus group and invite members. Membership signifies that an individual is authorized to see the DCC's reviewable data.
> 
> Once each group is created, assign reasonable manager & administrator roles. Then provide detailed instructions to the managers/administrators on how to manage the group.
> 
> NOTE: These groups are ONLY FOR THE CURRENT DATA REVIEW SPRINT (with October 2020 milestone). If we decide to continue using them for some other purpose later on, that needs to be an explicit decision. Otherwise, these groups are limited to use in the current epic and no further.

**Comment by jrchudy** [comment]
In regards to adding signup links into the navbar, I had commented the following in the EPIC 1 statement document:
> If the signup link differs per DCC, this might have to be another dropdown menu we add to the left side of the navbar. 

Seeing the above, sounds like we won't need to do what I mentioned above for this sprint. Once these groups are created, we can use them to control what links the user sees in the navbar based on group membership.

**Comment by lliming** [comment]
Globus groups are really easy to create and quite flexible. Once someone (anyone) creates a group, it can be administered (reconfigured) and managed (members added/removed/approved) by other people. 

1. I would be happy to either create the groups myself and assign others to adminster & manage them, or write up instructions for how to do that. Please let me know which you'd rather I do.
2. Can we get some clarity regarding who in the CFDE team will be managing members in these groups? I recommend at least one CFDE person be authorized to add members and assign admin roles for each group.  Who would that be?  I envision this being members of the DCC engagement team, but that's just my guess and may be wildly mistaken.

**Comment by ctb** [comment]
> 2. Can we get some clarity regarding who in the CFDE team will be managing members in these groups? I recommend at least one CFDE person be authorized to add members and assign admin roles for each group.  Who would that be?  I envision this being members of the DCC engagement team, but that's just my guess and may be wildly mistaken.

yes, agreed!

I think Amanda and I should both have such privileges, along with perhaps
Jeremy Walter as a backup.

**Comment by ACharbonneau** [comment]
That works for me. I will need management instructions though please :)

**Comment by lliming** [comment]
The following Globus groups are created and both @ACharbonneau and @ctb are administrators of each group. At this point, you may remove me from the group membership if you prefer that I not be a member. I don't mind either way, but it might be best to do that whenever the groups begin to be used to control access in the portal.

Group Name | UUID
-- | --
NIH CFDE GTEx Reviewers | 7977181e-f82f-11ea-b43a-0efde36f5027
NIH CFDE Kids First Reviewers | 1863c500-f831-11ea-b43d-0efde36f5027
NIH CFDE HMP Reviewers | 4e335e29-f831-11ea-b43e-0efde36f5027
NIH CFDE MoTrPAC Reviewers | 8a32410e-f831-11ea-880f-0ac4e6b272c3
NIH CFDE Metabolomics Reviewers | f423d7d8-f831-11ea-a93a-0a738d2d09bf
NIH CFDE LINCS Reviewers | 2b14318d-f832-11ea-880f-0ac4e6b272c3
NIH CFDE 4DN Reviewers | 642533ba-f832-11ea-880f-0ac4e6b272c3

Generic Globus group admin guide is [here](https://docs.globus.org/how-to/managing-groups/). I am working on specific recommendations for managing these Epic 1 groups (onboarding DCC reviewers) in a separate issue, so I'm closing this one.
