### ISSUE TITLE
Create a way to easily contact people about Cross Pollinations

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#183]
@jeremywalter is looking into making a list in Groups.io

**Comment by ACharbonneau** [comment]
Ideally, I'd like to bulk add a couple hundred people *without* notifying them they've been added. Just to cut down on email clutter. If it won't let us stealth add them, make sure the list is set up so that they get an informative welcome email. Also make sure *before* we start adding people that it's set up nicely:

-  that every email tells them how to unsubscribe. Like a legit mailing list
- informative links
- calendar is set up
- welcome email (or every email footer really) should have link to how to get to calendar

**Comment by jeremywalter** [comment]
I don't know how to stealth add people to mailing lists. Hopefully knowing you're on the mailing list with one frivolous e-mail won't dissuade too many people from participating. Otherwise I'm setting up a groups.io and attempting to integrate a calendar and escape options.

**Comment by ctb** [comment]
On Thu, Sep 10, 2020 at 12:18:02PM -0700, Jeremy Walter wrote:
> I might have a friend in Nigeria who can help out, but otherwise I don't know how to stealth add people to mailing lists. Hopefully knowing you're on the mailing list with one frivolous e-mail won't dissuade too many people from participating. Otherwise I'm setting up a groups.io and attempting to integrate a calendar and escape options. 

I think there are options here... what does the carpentries use?

**Comment by ACharbonneau** [comment]
https://carpentries.topicbox.com/

**Comment by jeremywalter** [comment]
Does this seem like an okay thing?
https://groups.io/g/CrossPollinationEvents
People can add themselves with a link. I have created a calendar and started populating it with events. It has super easy Zoom integration (as you are probably aware?). I had some of the team log in and it seems to work okay... does it tick all the boxes?

**Comment by jeremywalter** [comment]
First test of above groups.io successful. Second test happening today to test RSVP and Reminder features.

**Comment by jeremywalter** [comment]
groups.io is deployed and will be populated Monday...
