### ISSUE TITLE
Build a calendar for CP events

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#184]
presumably in groups.io 

set up zooms for each in the calendar

**Comment by ACharbonneau** [comment]
dates: https://github.com/nih-cfde/training-and-engagement/issues/11

**Comment by ACharbonneau** [comment]
@jeremywalter can you do a reality check to make sure that none of our dates are on holidays/so close to holidays that no one is gonna come? we might need to rearrange/kill some of the late November stuff

**Comment by jeremywalter** [comment]
I do not see any (holidays don't generally fall on Tuesdays)... Veteran's Day falls on the a Wednesday after a meeting and another meeting happens 2 days BEFORE Thanksgiving. I think this is okay?

**Comment by ACharbonneau** [comment]
no one works the week of thanksgiving. which one is it?

**Comment by jeremywalter** [comment]
The last one -- lightning talks part 2 --

**Comment by ACharbonneau** [comment]
ok. When you go to find lightning talk speakers, lets ignore that one until/unless the first one fills. And unless we have a ton of people who want to do it, kill it

**Comment by jeremywalter** [comment]
having built a calendar in the CP group which seems to be an unfortunately decapitated path, I will rebuild the calendar in Google hoping it will be more flexible/portable...

**Comment by jeremywalter** [comment]
I'm calling this done, though it still seems to be getting some tweaks. The calendar exists here: https://groups.io/g/CrossPollinationEvents/calendar
and is also built in Zoom.
