### ISSUE TITLE
Get people to volunteer to be speakers at lightning sessions

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#188]
So this is the Harmonization initiatives on 10/27/2020, DCC Lightning talks on 11/3/2020 and DCC Lightning talks on 11/24/2020

For Harmonization, we'll need a lightning talk from each funded DCC, and we have a specific format. 

For the others it's anyone who wants to volunteer. 

For all, we should have the lineup set at least 2 weeks before.

**Comment by ACharbonneau** [comment]
For the first session, we want to ask the newly funded DCCs, and we want to ask them to do lightning talks discussing their plans for their funded projects. We're emailing all the PIs on the grants, but make sure it's clear we only want one talk per DCC.

lets contact:

GTEx
------
- Kristin Ardlie
- Francois Aguet
- Jared Nedzel

SPARC
-------
- Peter Hunter
- Bernard de Bono
- Maryann Martone

Kids First
--------
- Adam Resnick
- Allison Heath
- Vincent Ferretti
- Jack DiGiovanna

LINCS
--------
- Avi Ma’ayan

IDG
--------
- Tudor Oprea
- Avi Ma’ayan

Metabolomics - **CONFIRMED**
--------------
- Shankar Subramaniam

ExRNA - **CONFIRMED**
--------
- Aleksandar Milosavljevic

HuBMAP
---------
- Jonathan Silverstein
- Katy Börner

**Comment by jeremywalter** [comment]
DRAFT INVITATION:

Greetings from the CFDE Coordination Team!

We are currently organizing Cross-Pollination events and are requesting that you or someone on your team present a short (8 minutes max) 'Lightning' talk via Zoom. There will be a brief (3 minute) Q&A after each presentation. The talk should present a highlights version of your planned, newly funded CFDE project(s).

 10/6/2020 | 11 AM PST / 2 PM EST | DCC Lightning talks 
 -- | -- | --  

Please reply to this mail to confirm by Thursday, September 24. 

Thank you for your participation!

The CFDE Coordination Team

----------------
Meeting Details:
--
Tuesday, October 6th, 2020
11:00am to 12:30pm PDT / 2:00pm to 3:30pm EST
https://zoom.us/j/8848247758?pwd=dGh1QnluRVh4T1ZtdTJFZzNUclpOUT09
Meeting ID: 884 824 7758
Password: 486352

**Comment by ACharbonneau** [comment]
ahh. I see. So. these were not meant to be the same format. Harmonization initiatives was going to be super lightning. like, 2 minutes to tell us what your requirements are, and all as one presentation. so DCCs work together beforehand to produce a single ~16 minute presentation

**Comment by jeremywalter** [comment]
Updated the draft... do we want any calendar or zoom links included in this particular mail? Is there a preferred deployment for this mail? (like... CC everyone in a gmail? or ???)

**Comment by ACharbonneau** [comment]
Sure if you have it. But let's make sure the description is right. I updated your email text

**Comment by ACharbonneau** [comment]
For the actual email

If you want to do just one: you should send ME the email, CC Owen, and BCC all the people you're actually sending it to.

Or, do one email per DCC (so then they'll know who else in their org you emailed) and CC me and Owen. 

Second choice is more annoying for you, but easier for the DCCs. 

Sending one mass email with all the names in the To box will cause a horrific nightmare of reply alls

**Comment by jeremywalter** [comment]
Missing e-mails:
**SPARC**
Peter Hunter
**Kids First**
Vincent Ferretti
Jack DiGiovanna
**IDG**
Tudor Opera
**ExRNA** -- _no contacts_
Aleksandar Milosavljevic
**HuBMAP**
Katy Borner

**Comment by AviMaayan** [comment]
Tudor I Oprea <TOprea@salud.unm.edu>

**Comment by jeremywalter** [comment]
Emails sent to everyone on this list, separated by org.

**Comment by ACharbonneau** [comment]
Cool. I can't remember if I made an issue for this, so either here, or in a specific issue please build the agenda for that meeting as you get volunteers.

**Comment by jeremywalter** [comment]
Agenda (Under Construction)
https://docs.google.com/document/d/1njHqjM5RE9jhmAi5orMtnvtakulcHFcGUm9HyYn1ATo/edit?usp=sharing

**ExRNA - Aleks
Metabolomics - Shankar**

- [ ]

**Comment by jeremywalter** [comment]
Sent Thursday Sept 24 

![image](https://user-images.githubusercontent.com/40613731/94302659-67480c00-ff21-11ea-82a6-4a3d9e8dde2b.png)

**Comment by jeremywalter** [comment]
Proposed: send out an [agenda](https://docs.google.com/document/d/1njHqjM5RE9jhmAi5orMtnvtakulcHFcGUm9HyYn1ATo/edit?usp=sharing) to participating DCCs with speaker roles filled in and TBD for those that haven't responded on Tuesday, Sept 29.

**Comment by jeremywalter** [comment]
Lightning talks concluded (for now)
