### ISSUE TITLE
Reminder emails before each event?

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#189]
I think we want to do this? Not sure if its for everyone, or just for registered people? DISCUSS

**Comment by ACharbonneau** [comment]
we should coordinate this with Wendy Knosp. we might need to get her on github

**Comment by jeremywalter** [comment]
without a registration process it seems kind of spammy, I'm not clear on how to navigate this subject in the community

**Comment by ctb** [comment]
I have lots of thoughts on this kind of thing. Happy to help brainstorm.

**Comment by jeremywalter** [comment]
Note: The Zoom integration in groups.io has an RSVP button -and- a reminders button.

**Comment by jeremywalter** [comment]
The reminders can be set up in the groups.io to ping everyone in the mailing list at adjustable intervals. If this is wanted, I will happily implement it.

**Comment by jeremywalter** [comment]
With the group mail list up, reminders can go live as directed.

**Comment by jeremywalter** [comment]
Reminders go out to preset default time zones (calibrated to the calendar). Users have to individually adjust their calendars for automation to be successful, SO I will be sending out manual reminders the day before each meeting. If instructed to I can also send a reminder 1 week before meetings to everyone in the group. 

Template for reminder e-mails is in this document:
https://docs.google.com/document/d/177tMS03Ki1JnPqYLHu3qazFS3NmD893bSrz4k6CucO0/edit?usp=sharing

**Comment by ACharbonneau** [comment]
I think that an email right after the event that says something like "we just finished blah, remember to join us next week for blah" would be good. And a reminder the day before. 

I'm open to moving the week before one to just before the this week event if someone else thinks that's a good idea.

**Comment by jeremywalter** [comment]
currently invitations go out the day of or day after a meeting with a reminder the day before... all going out through groups.io, but sent manually because the reminders function sends out mismatched timezones
