### ISSUE TITLE
Establish a place to hold all the materials for the CP

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#190]
It needs to be relatively public so all attendees can get to it. Needs:

- Place to submit lightning talk materials
- Place for notes for meetings
- Place to store webinar presentations and videos

**Comment by jeremywalter** [comment]
I have seen a lot of back and forth on where to put things... mostly on where not to put things. Would a Cross_Pollination folder in the CFDE Everyone be appropriate? Or a big Cross_Pollination folder to keep it separate and then subfolders for meeting notes, presentation materials, and recorded presentations?

**Comment by s-canchi** [comment]
Are the kickoff meeting materials in the CFDE Everyone ? The CP folder would make sense in the same drive as it.

**Comment by ACharbonneau** [comment]
nope. that's why I assigned myself to this one too. I have to make you a place. one moment

**Comment by ACharbonneau** [comment]
Here is your folder: https://drive.google.com/drive/u/2/folders/0AEcWOATavB8DUk9PVA

You'll need to configure the settings. I recommend that you make everyone who isn't you (or me) a "Contributor" so that you can manage the organization without people breaking it. But, you do you.

**Comment by jeremywalter** [comment]
established with sub-folders for recordings, notes, slides, etc
