### ISSUE TITLE
Assign scribes and get meetings on their calendars

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#191]
Team @nih-cfde/training is mediating all these discussion events. You need to get at least 2 (preferably 3) note takers per event, make sure they know where they're taking notes, and make sure they're all there and good to go.

**Comment by jeremywalter** [comment]
Clarification: does this mean that 2 or 3 out of 5 of our team should be taking notes at every meeting? Or should I be looking further afield for scribes?

**Comment by ACharbonneau** [comment]
You can try to get people who are not in our lab to do it if you want, but I suspect your luck there will be negative

**Comment by ACharbonneau** [comment]
also note #192 but, it's your show, you pick who to manage :)

**Comment by jeremywalter** [comment]
https://docs.google.com/spreadsheets/d/1f9Zs53kAao6WJejI1n-eW6K5EF45Gehc3vNYontYw3Y/edit#gid=0

Scribe sign-up

 Date | Scribe 1 (PhD) | Scribe 2 
 ----  | --------- | ------- 
09/29/2020	| Abhijna| Jeremy
10/13/2020	| Marisa	| Jeremy
10/20/2020	| Saranya	| Abhijna
10/27/2020	| Marisa   | Jeremy
11/10/2020	| Saranya	| Abhijna
11/17/2020	| Saranya	| Jeremy

**Comment by jeremywalter** [comment]
Complete
