### ISSUE TITLE
Meeting outcome overviews

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#192]
For each meeting with discussion, the scribes should put together a short (half page to a page) overview of outcomes from the meeting that we can distribute. I want the overviews to be out before the next meeting (so like, within a few days), because in a lot of this meeting series, the meetings build on one another. So you'll need to keep people on task a bit.

**Comment by jeremywalter** [comment]
Meeting Summaries end up here and linked in agendas:
https://drive.google.com/drive/folders/1ZbDeyHEVs7CX9atTmueMwmiUEoQd4jkJ?usp=sharing

**Comment by jeremywalter** [comment]
This process converted to curated transcripts that are available in the same folder as recordings and linked in all agendas.
