### ISSUE TITLE
Pre-setup spaces for DCCs

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#196]
Before you can start scheduling the onboarding meeting for a DCC, each onboarding DCC will need:

- A top level folder in the shared google drive
- A github repo:
   - with the correct permissions
        - maintain for everyone on that DCCs team, write for any collaborating DCC team, read for everyone else
   - with the correct issue template 
- A personalized version of [the agenda](https://github.com/nih-cfde/training-and-engagement/issues/195#issuecomment-690755436) saved in their google drive space
- Make a running agenda for that DCCs bi-weekly PM meeting

**Comment by ACharbonneau** [comment]
You can start setting up spaces now for 

- SPARC
   - [x] google drive folder
   - [x] github repo
   - [x] onboarding meeting agenda
   - [x] running agenda
- LINCS
   - [x] google drive folder
   - [x] github repo
   - [x] onboarding meeting agenda
   - [x] running agenda
- Kids First
   - [x] google drive folder
   - [x] github repo
   - [x] onboarding meeting agenda
   - [x] running agenda
- GTEx
   - [x] google drive folder
   - [x] github repo
   - [x] onboarding meeting agenda
   - [x] running agenda

**Comment by josesanchez1815** [comment]
Update: Jose needs to do this for 

- Metabolomics
- IDG
- Ex-RNA
- HubMap

**Comment by josesanchez1815** [comment]
Done!
