### ISSUE TITLE
Communication strategy

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#20]
Re: https://github.com/nih-cfde/deliverables/issues/87

We need to make a communication strategy. Due end of June.

We have a draft one from 2019 to use as a starting point

**Comment by dcfcjcheadle** [comment]
Hi @ACharbonneau and @RLC-DCPPC,

I integrated training information into the [communication strategy draft](https://docs.google.com/document/d/1-AUoz6ccQs88BV3DlnjrSJEULPumvTLQRNYb7-BQOUg) using the training plan deliverable as a guideline.  I also updated the website section to incorporate websites other than the nih-cfde.org website.  New sections are marked by comments.  Please let me know what comments/suggestions you have.

Thanks,

John

**Comment by ACharbonneau** [comment]
Hi! Sorry, I didn't realize you assigned yourself to this. The NIH has assigned us a Communications person, that we've met with a couple of times, and there are some specific things we need to cover in this plan to align with the overall NIH strategy. Titus has a new/different outline that he presented to her at our last meeting. I'll look to see what we might be able to use from this draft to fit her requirements. @ctb

**Comment by dcfcjcheadle** [comment]
Understood!  Hope some of it is usable and thanks for letting me know -

**Comment by ACharbonneau** [comment]
https://docs.google.com/document/d/1kCEuireJ6HBd4pfR7XsZG3RWp5Vhb_P2krmoJGcBB3I/edit?usp=sharing
