### ISSUE TITLE
KF download data tutorial -- vidlet suggestions

### ISSUE THREAD

**Issue by abhijna** [nih-cfde/training-and-engagement#200]
Comments for Terminal vidlet: wget to download data (From @s-canchi )

The actual content starts between 2-3 seconds and would be good to edit out the initial message about z shell
Actual commands are run within the first minute and 30 seconds and the remainder video is the download process. Maybe edit it out to show the final result ?
Some inconsistency in comment text format with capital and small letters
Empty command lines are distracting
Comments for Terminal vidlet: clean up file names

The actual content starts between 2-3 seconds and would be good to edit out the initial message about z shell
Long pauses between comments and code stretch out the video. Maybe edit it out to show the final result ?
Might work better to use ls -1 to show the filenames since it is a long string
Some inconsistency in comment text format with capital and small letters
Empty command lines are distracting
Observation: Both the screencasts show the cast ID on mouse hover and have the Recorded with asciinema in the bottom left corner.

If you have the original screencast copies, I will be happy to help configure it.

**Comment by abhijna** [comment]
@marisalim @jeremywalter @josesanchez1815 
Can you all please look at [these screencasts](https://training.nih-cfde.org/en/latest/Bioinformatics-Skills/Kids-First/Download_Data/Data-Download-Via-Cavatica/) and give me your thoughts? 

@s-canchi already gave her comments (read above). 
I really rather not make them again if possible :(

**Comment by marisalim** [comment]
is it possible to crop asciinema screencasts? the only edits I'd make for now would be to trim off the multiple `exit` statements at the end of the `wget` vidlet.. maybe the first bit with z shell too. 

i think the spaces between the code lines make it easier to read actually, so i'd leave that formatting in. the download jumble of text can be intimidating, so i think it's helpful to show this is a normal output of running the `wget` command.

**Comment by jeremywalter** [comment]
I don't think I have any particularly useful feedback to add... I can drop a couple of comments for future thoughts:
1) there are some typos (but that's pretty hard to avoid in live screen cast (the first is the word desktop (DEsktop) in the first line of text... 
2) speed... I don't see a speed-up option, so typing out a lot of text can mean the viewer has to be quite patient
3) funny stuff -- I like 'whoah' and 'crazy stuff'... but I'm not sure if the general audience will be as on board with that as I am (I could be totally wrong, but something to consider?).

I do like the format and and set-up for the lesson and I think the screencast is pretty neat and less intrusive than being forced to watch a video tutorial.

**Comment by abhijna** [comment]
I managed to edit it!!! It was a crazy amount of mindless work. But it looks pretty good now I think:
https://asciinema.org/a/Z8T6lt0UHjHXw5YNA7dzyUDF2

**Comment by marisalim** [comment]
Nice! Please share how you edited the screencasts! :) i can add notes to the style guide.

**Comment by abhijna** [comment]
This is the second vidlet:  https://asciinema.org/a/eYJihFaM7c4TlTRavNAy3IkOO

**Comment by abhijna** [comment]
How to edit asciinema screen casts:

1) Download the screencast from your asciinema account (.cast file)
2) Open in text editor (e.g. atom)
3) The file looks like this:

```
{"version": 2, "width": 75, "height": 18, "timestamp": 1598395763, "env": {"SHELL": "/bin/bash", "TERM": "xterm-256color"}}
[0.01083, "o", "\u001b[?1034hbash-3.2$ "]
[1.548746, "o", "\u001b[H\u001b[2Jbash-3.2$ "]
[3.362292, "o", "#"]
[3.849687, "o", " "]
[4.105164, "o", "F"]
[4.25718, "o", "i"]
[4.328995, "o", "r"]
[4.434286, "o", "s"]
[4.61828, "o", "t"]
[4.790068, "o", " "]
[5.031393, "o", "l"]
[5.125048, "o", "e"]
[5.22469, "o", "t"]
[5.396713, "o", "'"]
[5.556953, "o", "s"]
[5.755022, "o", " "]
[5.932595, "o", "c"]
[6.061395, "o", "h"]
[6.14247, "o", "e"]
[6.27824, "o", "c"]
[6.402957, "o", "k"]
[6.54971, "o", " "]
[6.671492, "o", "t"]
[6.794996, "o", "o"]
[6.880366, "o", " "]
[7.037239, "o", "m"]
[7.132153, "o", "a"]
[7.254111, "o", "k"]
[7.377614, "o", "e"]
[7.490531, "o", " "]
[7.607784, "o", "s"]
[7.762003, "o", "u"]
[7.863834, "o", "r"]
[7.926838, "o", "e"]
```
4) You can edit timestamps to speed or slow things down, crop the video, and edit the words, capitalization, spacing, etc that appear on the screen cast. 

5) Save you changes and view those changes as you go by replaying on your terminal using this command:

```
asciinema play /path/to/screencast/2_screencast.cast
```

6) When you are ready to upload to your asciinema profile:
```
asciinema upload /path/to/screencast/2_screencast.cast
```

7) All done!

**Comment by josesanchez1815** [comment]
Wow, this looks like it was a lot of work. Thanks Abhijna!

**Comment by marisalim** [comment]
use this syntax to embed local .cast files in tutorial markdown:

```
<asciinema-player src="../mime_supplementary_files/mimetype_screencast.cast" speed="2" theme="tango" font-size="medium" cols="60" rows="15" poster="data:text/plain,\x1b[1;37mTerminal Vidlet for mimetype"></asciinema-player>
```
