### ISSUE TITLE
Slack channel set up for CP

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#202]
As part of registration, you might want to give people the option to join slack, in particular to [this slack channel](https://join.slack.com/share/zt-hf0ghcok-DSFThbD_AJ5JhTbPc5tG7A) as we did with the January meeting. It could be a good place to do reminders as in #189 and it allows for cross talk during talks without interrupting the speaker. 

thoughts @ctb ?

**Comment by ACharbonneau** [comment]
The slack invite I linked above expires after 7 days, we'll have to refresh it if we go this route

**Comment by ACharbonneau** [comment]
actually, having thought about it an extra 30 seconds. our paid group.io is *already configured* to invite everyone to slack, so if you just made crosspollination a subgroup of our regular groups io, they'd get an invite if they wanted it

**Comment by ctb** [comment]
On Fri, Sep 11, 2020 at 01:25:38PM -0700, Amanda Charbonneau wrote:
> As part of registration, you might want to give people the option to join slack, in particular to [this slack channel](https://join.slack.com/share/zt-hf0ghcok-DSFThbD_AJ5JhTbPc5tG7A) as we did with the January meeting. It could be a good place to do reminders as in #189 and it allows for cross talk during talks without interrupting the speaker. 
> 
> thoughts @ctb ?

yes!

**Comment by jeremywalter** [comment]
https://join.slack.com/share/zt-heyno65h-8ulXD17qsKsFGqNq4ie08w

link to join the cross-pollination slack channel in CFDE group (should not add people to the group) -- as noted this will have to be refreshed weekly -- OR I can just include my contact for people ping me if they encounter the expired version.

**Comment by jeremywalter** [comment]
I added the above (updated) link in a recent CP communication and a couple people clicked on it. I approved a person from a DCC and a member of our team. This triggered a paid feature in Slack which would require dib-lab to go on a paid subscription with 90 days or potentially lose stored data and triggered features. This might explain why the first person that joined, and was approved, immediately left. I don't know what the best solution would be... keep above system and explain it to DCCs that free plans will be triggered into a trial mode, or open a new CP Slack Channel.

Slack wisdom and direction needed!

@ACharbonneau @ctb

**Comment by ACharbonneau** [comment]
i sent Jeremy a better link. We should add it to the meetings with a note that it is an updated link

**Comment by jeremywalter** [comment]
~~https://join.slack.com/t/cfdeworkspace/shared_invite/enQtOTM0MDQ5NjU4NDM2LWIxNDE4OTI3N2NmZjdkZmMwYjkzNzQwYzM0NTY4ZjZmY2I1NDhjMWFmZDM1YTkxY2YxYzQ4ZTEwNTlkNDgxNjc~~

https://join.slack.com/t/cfdeworkspace/shared_invite/zt-hupdgmhw-ZzSUc8Oau3DTpfBr4PccKg
