### ISSUE TITLE
onboarding instructions for DCC reviewers for Epic 1

### ISSUE THREAD

**Issue by lliming** [nih-cfde/training-and-engagement#207]
We need a simple, easy-to-follow set of instructions for DCC PIs that tell them how to get their authorized reviewers onboarded. 

- At its most basic, this will be of the form, "Send us the ID of the person you want to authorize."
- But we'll need a little more detail than that. For example: How do I get the right ID for each person? Where do I send it? And maybe: How can I get the list of people I've authorized?

@lliming will provide a first draft of the part about finding the right ID for each person.

**Comment by ctb** [comment]
did you just third-person yourself? 😄 

I think we should require that they be onboarded to the CFDE in the traditional sense, first (or as part of this).

**Comment by ACharbonneau** [comment]
oh man. we probably do need to make getting added to deriva groups a part of onboarding. I hadn't considered that. I think for Real Life™ we should roll it into our onboarding form and process, but for this first go at getting people in, I think we'll just ask them to onboard concurrently. Most of the relevant people will be onboarding as part of their FOA funding anyway.  

cc: @nih-cfde/coordinators can ya'll make a note we need to update onboarding for this

**Comment by lliming** [comment]
Can I get a link to the current onboarding process/description? I'm curious to see if there may be something that's already being done that would simplify this process (getting added to a review group) for people who've already been onboarded, or who are getting onboarded as part of this process. Thanks!

**Comment by ACharbonneau** [comment]
From a onboarding human point of view, the process is:

- Go to [our welcome site](https://cfde-welcome-to-cfde.readthedocs-hosted.com/en/welcomefixes/General_Onboarding/)
- Fill out the form there and refer back to site with any questions

From an onboarding team point of view the process is [documented here](https://github.com/nih-cfde/organization/blob/master/infrastructure/OnboardingWorkflow.md)

**Comment by ACharbonneau** [comment]
For the record, I'm open to re-jiggering the onboarding if there's ways to make it more automated. Right now we have to add people to each resource (github/google/groups.io) individually as only groups.io and slack will talk to one another.

**Comment by ACharbonneau** [comment]
@lliming in https://github.com/nih-cfde/training-and-engagement/issues/176#issuecomment-693535998 you mentioned that  "I am working on specific recommendations for managing these Epic 1 groups (onboarding DCC reviewers) in a separate issue" Is that this issue? or another one? I think you said you had finished it, but I'm struggling to find things today :(

**Comment by lliming** [comment]
Here is the issue:
https://github.com/nih-cfde/security/issues/6

And here is the doc with the recommendations in it:
https://github.com/nih-cfde/security/blob/master/epic-1-groups/epic-1-groups.md

**Comment by ACharbonneau** [comment]
thank you!

**Comment by ACharbonneau** [comment]
We now have basic instructions here: https://github.com/nih-cfde/published-documentation/wiki/Onboarding-to-the-CFDE-Portal-Submission-System

@jeremywalter  We still need:

-[ ]  some kind of tracking system that is better than my [associated github issue](https://github.com/nih-cfde/training-and-engagement/issues/345)
-[ ] an updated process document for the onboarding team to follow when adding/removing people [original version is here](https://github.com/nih-cfde/security/blob/master/epic-1-groups/epic-1-groups.md)

**Comment by jeremywalter** [comment]
@ACharbonneau asking because I don't want to duplicate work: I can make a .md tracker grid in the github issue, or a google sheet to link to... atm I'm leaning towards the issue

**Comment by ACharbonneau** [comment]
so...we need to do on and off boarding for these indefinitely. Having it in an issue is terrible. It is like this because I have not had time. I'm asking you to create a good onboarding for this system, not a random transient thing.

**Comment by ACharbonneau** [comment]
Since this was proximately completed, I'm closing so we can close the epic and moving the new tasks to a new issue.
