### ISSUE TITLE
Update KF tutorial landing pg

### ISSUE THREAD

**Issue by marisalim** [nih-cfde/training-and-engagement#219]
update the landing pg following style guide - move Portal overview content to landing pg for description, learning objs, table of contents, and prereqs.

**Comment by marisalim** [comment]
@abhijna did we come to a conclusion about whether the ORCID id is required for the KF tutorial? The tutorial says ORCID, but you seem to be working fine with Google. Should I add that either works in the prereqs section?

**Comment by abhijna** [comment]
oops, i changed it in the download data page but forgot to edit that in the prereqs. yes, please change :)
