### ISSUE TITLE
Fix website images to include hyperlink text

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/training-and-engagement#221]
In the current website mouse hover on an images shows magnifying icon instead of the alternative text. This has to be corrected to meet accessibility requirements. This will be fixed in the next release using an updated image syntax.

From @marisalim 

> Solution to: "Feature: Alternative text on mouse hover - Addresses accessibility concern with the current image zoom function which shows a magnifying mouse icon instead of the alternative image text. This needs to be fixed."
> 
> Add the text in quotes after file path - that text is visible when hovering over image:
> 
> `![Table View](../../images/KidsFirstPortal_37.png "Table View")`
>

**Comment by marisalim** [comment]
note that i figured this out from working on the KF tutorial, so it should be good to go, unless anyone wants to edit what the text says.

we'll need to double-check the images in the rest of the tutorials.

**Comment by marisalim** [comment]
tracking tutorials with image syntax that has been edited:

tutorial | status
--- | ---
KF | done
Gen Tutorial AWS | done
cfde-bot | done
Snakemake | done
GWAS | done
AWS | done
CFDE portal | done

(add any that are missing from this list)
