### ISSUE TITLE
CP Schedule + RSVP numbers

### ISSUE THREAD

**Issue by jeremywalter** [nih-cfde/training-and-engagement#231]
This issue will update and track RSVPs for upcoming Common Fund Data Ecosystem (CFDE) Cross-Pollination Events. These numbers can be found by clicking on the calendar events in groups.io and then the View Responses button for RSVPs at the bottom of each event: https://groups.io/g/CrossPollinationEvents/calendar

Date | Meeting | RSVPs | Actual
-- | -- | -- | --
6/1/2021 | CurIndex | |
5/10/2021 | CFDE Program Meeting | | 
5/4/2021 | IDG | |
4/6/2021 | HuBMAP & ExRNA | |
3/16/2021 | R03 Lightning Talks 2 | |
3/2/2021 |  Metabolomics & GTEx | |
2/16/2021 | R03 Lightning Talks |  14 |
2/2/2021 | NIH & LINCS | 21 |
1/5/2021 | Kids First & CFDE-CC | 25 | 86
12/1/2020 | Establishing the CFDE Anatomy Working Group | 2 | 54
11/17/2020 | CFDE Connections and Data Sharing | 24 | 68
11/10/2020 | CFDE Portal Demo and Roadmap | 33 | 71
10/27/2020 | Harmonization Initiatives | 39 | 83
10/20/2020 | C2M2 Workshop | 36 | 74
10/13/2020 | C2M2 | 43 | 79
10/6/2020 | DCC Lightning Talks | 51 | 76
9/29/2020 | How to Engage with the CFDE-CC | 43 | 92

**Comment by s-canchi** [comment]
It will be good to add the actual attendance column for the event to this table to compare. Are we keeping track of participants list for each event and is there a way to export the list from zoom ?

**Comment by jeremywalter** [comment]
yes, further tracking is happening... this issue is just for the RSVPs as it has specifically been requested

**Comment by jeremywalter** [comment]
The new registration system does not have RSVP capability since we moved to an Outlook based invitation system.
