### ISSUE TITLE
Naming tutorials

### ISSUE THREAD

**Issue by jeremywalter** [nih-cfde/training-and-engagement#238]
For a more consistent and visually pleasing web-site and easier construction of release notes I suggest adopting a formal naming convention for tutorials:

- [ ] using formal capitalized titles (example):
+  Rendering a GitHub website locally with Jekyll -> Rendering a GitHub Website Locally with Jekyll

- [ ] including titles (or agreed upon shorthand) in PR titles (example): 
+ Rendering a GitHub website locally with Jekyll -> Rendering/Jekyll

Other thoughts/ideas welcome!

**Comment by s-canchi** [comment]
On a related note, it would be good to have some of template or format for the PR titles as well that give information of the tutorial title, and main point of the PR.

**Comment by marisalim** [comment]
When we do the great nav bar tab reorganization, we could edit a few of the titles since we'll be editing the file paths anyways... i.e., if there are obvious title candidates to edit.

**Comment by jeremywalter** [comment]
From the Google sheet... these are the ones that I would rename
Old | New 
-- | -- 
| Rendering a GitHub website locally with MkDocs | **Rendering a GitHub Website Locally with MkDocs** 
| Editing Mkdocs websites with cfde-bot | **Editing MkDocs Websites with cfde-bot**
| Set up Conda computing enviornment | **Setup Conda Computing Environment**
| Rendering a GitHub website locally with Sphinx | **Rendering a GitHub Website Locally with Sphinx**
| Identifying MIME types | **Identifying MIME Types**
| CFDE portal | **CFDE Portal**
