### ISSUE TITLE
Reorganization of the tutorial resources

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/training-and-engagement#239]
Currently we host tutorial images under one centralized folder but host additional tutorial resources such as screencasts, example files, scripts etc within the tutorial folder. With the growing list of associated images, it would be better to reorganize the images into either tutorial specific folders or split them back to the original tutorial folder. The tutorial specific resources will also be unified to remove any ambiguity. This is internal organization and will not impact the website render.

**Comment by s-canchi** [comment]
Are we still doing this for Dec release ?

**Comment by marisalim** [comment]
reorg tutorial images into separate subfolders within tutorial folders. 

- [x] reminder to @marisalim to edit the style guide to update where to save images + "Est. cost" tab for cloud computing tutorials
