### ISSUE TITLE
Customize social media icons location 

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/training-and-engagement#240]
The social media icons and the links by default render in the footer of the website. It would be preferable if they appear next to the search bar on the top right corner. 

<img src="https://user-images.githubusercontent.com/62918474/96287301-94269680-0f96-11eb-9963-e7e318675798.png" width="800" height="400" />

**Comment by josesanchez1815** [comment]
I would like to try and look into this too!

**Comment by abhijna** [comment]
Feel free to assign yourself Jose :)

**Comment by josesanchez1815** [comment]
Small Quick notes for Jose
Relevant Files:
- mkdocs.yml
- extra.css
- [Customize Icons In Material for Mkdocs](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)
- [HTML+CSS](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/style)

The Attribute List extension, which is part of the standard Markdown library, allows to add HTML attributes and CSS classes to Markdown elements, and can be enabled via mkdocs.yml
