### ISSUE TITLE
Update landing page with image slider

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/training-and-engagement#245]
Integrate the landing page with a image slider which is clickable linked to the lessons as a way to offer the user the different tutorials that are available. The slider should be customizable and should work on multiple platforms and modes.

**Comment by s-canchi** [comment]
Suggestions on what the front matter should look like including images are requested. A dedicated format, color scheme and content are all up for discussion.

**Comment by s-canchi** [comment]
From @ACharbonneau 

> You might want to see if you can edit the template for the front page to not have sidebars. Depending on how the material theme is written this could be anywhere from trivially easy to next to impossible

**Comment by ACharbonneau** [comment]
Did you already try lightbox? there's a recipe for mkdocs: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Recipes#lightbox-add-on-using-theme_dir

**Comment by ACharbonneau** [comment]
Replacing the TOC recipe: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Recipes#remove-the-table-of-contents-sidebar-from-the-mkdocs-theme

**Comment by s-canchi** [comment]
I have been working on solutions and this is what the website looks like now:
![Screen Shot 2020-10-22 at 10 35 11 AM](https://user-images.githubusercontent.com/36385305/96909107-68058c80-1452-11eb-9830-29b5ff7c98ad.png)

There are more things to fix and I have slowly been testing out the different features to make them responsive.

**Comment by abhijna** [comment]
look very nice @s-canchi! Is this in compliance with the new theme?

**Comment by s-canchi** [comment]
The colors are customizable. The blue is from our current style guide and the teal was close to the proposed style guide.

**Comment by marisalim** [comment]
looks nice! how do the other sections look? e.g., Bioinformatics Skills landing pg

**Comment by s-canchi** [comment]
Not very different except the footer color.
![Screen Shot 2020-10-22 at 10 58 52 AM](https://user-images.githubusercontent.com/36385305/96911441-b5372d80-1455-11eb-8d7c-ad91fa453af5.png)
![Screen Shot 2020-10-22 at 10 59 06 AM](https://user-images.githubusercontent.com/36385305/96911451-b700f100-1455-11eb-8502-966617f49c5d.png)
