### ISSUE TITLE
Create valid testing data submission

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#256]
@ACharbonneau commented on [Fri Oct 30 2020](https://github.com/nih-cfde/planning-docs/issues/80)

**Comment by ACharbonneau** [comment]
We're getting rid of the concept of 0 and 1, and it's also really unclear how to build a useful toy dataset. I think what we really want is a "this will for sure validate" dataset instead, that someone can use to be sure their submission tool works

**Comment by abradyIGS** [comment]
there's a minimal valid submission [here](https://osf.io/uadny/).

am working now on a more complicated one; will return with a link when ready.

**Comment by abradyIGS** [comment]
there's now a more complicated valid submission sample at the same OSF link as the one i gave in the previous comment. if you agree this suffices, please review & close.

**Comment by marisalim** [comment]
Hi @abradyIGS! just wanted to check - I noticed that the files you added are private. Is that intentional or can I make them public?

**Comment by abradyIGS** [comment]
ack, that was ignorance on my part of the default access settings. everything i posted should be public; i flipped two just now and think i've fixed the permissions everywhere they were incorrectly private, but if any remain, feel free to just flip them to public. thanks for the catch!

**Comment by marisalim** [comment]
no worries, thanks @abradyIGS it all looks good now!
