### ISSUE TITLE
Tutorial/walkthrough of data submission process

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#258]
@ACharbonneau commented on [Thu Oct 15 2020](https://github.com/nih-cfde/planning-docs/issues/75)

**Comment by ACharbonneau** [comment]
@nih-cfde/training Can't remember if this was in my list, but I'd like a tiny tutorial for this in the style of https://github.com/nih-cfde/published-documentation/wiki/How-to-approve-your-datapackage

**Comment by s-canchi** [comment]
I will work on this later today.

**Comment by s-canchi** [comment]
The mini tutorial was added: https://github.com/nih-cfde/published-documentation/wiki/How-to-submit-a-datapackage

**Comment by ACharbonneau** [comment]
for this step:
Your DCC needs to be registered in the portal and have the correct permissions set up to be able to submit datapackages. The OnBoarded DCC page in the portal lists all the registered DCCs. Contact the CFDE-CC helpdesk to register your DCC if not on the list.

can they see that page if they aren't onboarded???

**Comment by s-canchi** [comment]
I can see the page without logging into the portal. Will confirm with the team if that is the general case.

**Comment by ACharbonneau** [comment]
huh.
