### ISSUE TITLE
Documentation for configuring Data Submission Tool

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#259]
A user should be able to consult this documentation and learn how to a acquire, install and configure the submission tool

**Comment by s-canchi** [comment]
Is the tool already available ? If so where can I find it and does it have some guidelines to get started ?

**Comment by ACharbonneau** [comment]
I'll update this with info when I have it.

**Comment by jgaff** [comment]
@NickolausDS and I have made this document on the tool's installation and usage: https://github.com/nih-cfde/cfde-submit/blob/client-dev/README.rst
Does that address this use case sufficiently?

**Comment by ACharbonneau** [comment]
@jgaff This is great :) Is the infrastructure such that I can run through and test it to make sure the instructions work?

**Comment by jgaff** [comment]
I believe the Production environment may not be ready, but I think Staging would be usable. @NickolausDS is that accurate?
You can select an environment with the flag `--service-instance=env_name` for `dev`, `staging`, or `prod` (this option isn't in the README documentation because as I understand users are not intended to ever use non-Prod environments).

**Comment by ACharbonneau** [comment]
excellent. thanks!

**Comment by NickolausDS** [comment]
Yes, Production isn't running and that will cause you to get a warning when using the cfde-submit client. However, you can still run it using the dev or staging environments:

```
pip install cfde-submit
cfde-submit login
cfde-submit run --service-instance staging <my data package>
cfde-submit status
```

**Comment by ACharbonneau** [comment]
this has been updated, and will be included in the docs site https://github.com/nih-cfde/published-documentation/issues/138
