### ISSUE TITLE
CFDE Data Submission Work Group Meeting

### ISSUE THREAD

**Issue by josesanchez1815** [nih-cfde/training-and-engagement#266]
We need to start setting up Work Group Meetings: 
Details can be found below:

@ACharbonneau

**Comment by ACharbonneau** [comment]
@carlkesselman @owhite This is to set up the meeting Carl proposed today during the tech call. So that we can have data submitters work with us directly over the next couple months.

Who would be good on our side for attending this?

**Comment by josesanchez1815** [comment]
@carlkesselman @owhite
