### ISSUE TITLE
2021 Cross Pollination Series

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#268]
Every first Tuesday of the month we're having a CP event. Need to start working on the schedule and getting meetings setup.

Let's just use the same zoom meeting ID for all of them, and just not put it in the google space? We can send it out via the mailing list, and not post it publicly and that should be ok.

**Comment by ACharbonneau** [comment]
This is the epic that holds all the CP meetings for the new series. I did a lot of issue set up for the first meeting series, but for these, I'm still going to come to them all, and I'm fine with doing the hello/introducing the speaker, but I would like to be much, much less involved in making them all run. 

So, please make issues for the tasks you need to do and either do those things, or assign them out to people, and keep the issues up to date. Be sure to include hosts and moderators in the list of people you need to do things. Let's plan for each one to make a ~1 paragraph summary of what happened that can go into announcements and whatnot, but not super detailed notes, unless the speaker wants that.

**Comment by jeremywalter** [comment]
check with Katy Borner HuBMAP for a slot

**Comment by jeremywalter** [comment]
CP meetings are being organized through the helpdesk, the CFDE website, and the events calendar
