### ISSUE TITLE
Cross Pollination Meeting 0

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#269]
Dec 1 with SPARC https://github.com/nih-cfde/SPARC/issues/11
Title: Establishing the CFDE Anatomy Working Group

Contacts: Bernard de Bono (please contact by email when needed) and @jylb

**Comment by jeremywalter** [comment]
@ACharbonneau are there extra steps required of me here beyond sending out the invitations and setting up the zoom meeting (in line with what we've been doing up to now?). I read this as an extension of what we've been doing, but if I need to do something with the contacts above and for future meetings, please advise.

**Comment by jeremywalter** [comment]
Agenda template shared with SPARC team Nov 13, awaiting feedback and instruction on details for their meeting:

https://docs.google.com/document/d/1pw1qkHxn0UdVirYsEfiOlEMOMS9yE73Dy-FmnhaxK5M/edit?usp=sharing
