### ISSUE TITLE
New web address

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#270]
We're moving all the sites to be in the same domain. 

This one is going to be training.nih-cfde.org

Need someone in @nih-cfde/training to work out how we do a custom domain in RTD, preferably with either keeping the original address working or having some kind of redirect that keeps the original from just showing a 404.

I've got a bit of code in [this PR](https://github.com/nih-cfde/use-case-library-build/pull/38) that can be reused to tell people that the site is moving/has moved if we want that.

The new address doesn't quite exist yet, but lets get it figured out asap before we have a bunch of site users.

issue where new address is being made:
https://github.com/nih-cfde/use-case-library-build/issues/35#issuecomment-725491836

**Comment by ACharbonneau** [comment]
from Victor: The CNAMES have been defined. But none of the 3 seem to be honored by github or readthedocs.

**Comment by ctb** [comment]
On Thu, Nov 12, 2020 at 11:25:54AM -0800, Amanda Charbonneau wrote:
> from Victor: The CNAMES have been defined. But none of the 3 seem to be honored by github or readthedocs.

right, they need to be configured on the receiving end.

**Comment by s-canchi** [comment]
@ACharbonneau - what is the CNAME for the training website ? These are steps that need to happen for the current training website address to resolve to **training.nih-cfde.org** 
- Add a CNAME record from _af23275e7437771d056a644dc53948b9.training.nih-cfde.org to _verify362493cb.domains.readthedocs.com to verify ownership of your domain.
- Wait for SSL certificate issuance and domain configuration (this may take a few days).
- Add a CNAME record in your DNS pointing your custom domain to 362493cb.domains.readthedocs.com.

Modifications for the CNAME requires admin privileges on the provider end.

**Comment by ctb** [comment]
thanks, saranya!

a few comments --

## training.nih-cfde.org already resolves (via CNAME) to cfde-training-and-engagement.readthedocs-hosted.com
```
% host training.nih-cfde.org
training.nih-cfde.org is an alias for cfde-training-and-engagement.readthedocs-hosted.com.
cfde-training-and-engagement.readthedocs-hosted.com has address 52.88.254.68
cfde-training-and-engagement.readthedocs-hosted.com has address 52.89.161.221
cfde-training-and-engagement.readthedocs-hosted.com has address 35.160.205.89

% host -a training.nih-cfde.org
Trying "training.nih-cfde.org"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4641
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;training.nih-cfde.org.    IN   ANY

;; ANSWER SECTION:
training.nih-cfde.org.  300     IN      CNAME   cfde-training-and-engagement.readthedocs-hosted.com.

Received 104 bytes from 2600:1700:e1c1:3da0::1#53 in 268 ms
```

## the verification stuff etc will need to be done by the owner(s) of nih-cfde.org

I believe that's the UMD folk, so, out of our control.

**Comment by ACharbonneau** [comment]
I have no idea what I'm supposed to do here. If it is something other than nothing, please tell me.

**Comment by ctb** [comment]
> These are steps that need to happen for the current training website address to resolve to **training.nih-cfde.org**
> 
>     * Add a CNAME record from _af23275e7437771d056a644dc53948b9.training.nih-cfde.org to _verify362493cb.domains.readthedocs.com to verify ownership of your domain.
>     * Wait for SSL certificate issuance and domain configuration (this may take a few days).
>     * Add a CNAME record in your DNS pointing your custom domain to 362493cb.domains.readthedocs.com.

Hi @ACharbonneau I think that the DNS manager needs to take on the three tasks above -- I believe that's Victor, but I don't know his GitHub ID. I'll send this to him on slack.

**Comment by s-canchi** [comment]
The domain name has been successfully updated. The website is: https://training.nih-cfde.org/en/latest/

**Comment by ACharbonneau** [comment]
please close issues when they're done
