### ISSUE TITLE
Please update published slides from Arthur's webinars on 10/13 and 10/20

### ISSUE THREAD

**Issue by abradyIGS** [nih-cfde/training-and-engagement#275]
the versions of the two talks i've put [here](https://drive.google.com/drive/u/0/folders/1cRIRG2CPWb8M9XSKyM7BKNvRPUx9z-OH) supersede those posted [here](https://drive.google.com/drive/u/0/folders/1ufBh88ZLIPJBRWE5jH3DQ5awhIAjO_IJ).

i don't have edit access to the cross-pollination storage area: please remove the five copies of my two talks from [the CP folder](https://drive.google.com/drive/u/0/folders/1ufBh88ZLIPJBRWE5jH3DQ5awhIAjO_IJ) (2 PDF, 2 PPT and 1 Google Slides; **_all five need deleting_**) and replace those files with the two blessed Google Slides decks posted to [the other folder](https://drive.google.com/drive/u/0/folders/1cRIRG2CPWb8M9XSKyM7BKNvRPUx9z-OH).

(assigning to amanda for further delegation as appropriate; please let me know if anyone encounters any permissions issues retrieving the new versions)

**Comment by jeremywalter** [comment]
Copied and moved to the CP folder, old files in the trash.

**Comment by abradyIGS** [comment]
many thanks!
