### ISSUE TITLE
DCC data curators for interface guru interviews

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#279]
I need all of the PIs from all of the DCCs sent an email asking them to participate in interviews with interface guru. An email I sent earlier this year is below, you can just change the dates/times and reuse it.

Dates/times:

week of 12/14. Specifically Tuesday - Thursday, plus Saturday, for the dates. Let’s say 10am MT / 12pm MT / 2pm MT / 4pm MT. 

Be sure to list the times in Eastern and Pacific as well!

> Hello everyone,
> 
> We'd like to interview some volunteers about our portal user interface. This is a chance to tell us how you would like to review data from your DCC program(s) and to help us correct course on anything we’ve gotten wrong.
> 
> If you are available and interested in being interviewed, please respond to this email with your preferred date and time. Appointments for interview sessions are available on June 3rd, 4th, and 5th at noon, 2pm and 4pm each day.
> 
> Details:
> 
> The CFDE-Coordination Center is working to create a centralized portal for accessing data from Common Fund Programs. This portal will provide both an interface for end users to find new data, and an interface for NIH Program Officers, Data Curators and DCC PIs to see information about the data curated by their Programs. We have contracted a professional user interface design company, Interface Guru, to do a third party assessment of our tools and design, and are looking for approximately eight volunteers to participate in their assessment of the data submission interface. 
> 
> Each volunteer would participate in their own, approximately 1 hour long session with Interface Guru via video conference. During the session, you would be able to explore the current interface and tools, and to provide suggestions for new or different features.
> 
> If you have any questions please let me know, and thank you in advance for your participation,

**Comment by josesanchez1815** [comment]
@jeremywalter

**Comment by jeremywalter** [comment]
Jose deployed an e-mail and only got one response back offering a Friday (not available) meeting time. I contacted IG with this information and now they are conferring and checking in with tech on the state of wire frames. We await further direction on possible meeting times and participants.
