### ISSUE TITLE
Add a screencast to the Cavatica uploader tutorial?

### ISSUE THREAD

**Issue by abhijna** [nih-cfde/training-and-engagement#288]
Thoughts from @s-canchi 

Thinking as a user without much familiarity of the Cavatica interface, I like the visual impact of the screenshots with the circled sections, such that when I go back to the Cavatica interface I can go by visual memory instead of text. Clicking back and forth between two separate tutorials may not be ideal as we want to keep them modular, and hence my suggestion a screen-capture video which can be relatively quick to accomplish.

**Comment by jeremywalter** [comment]
More or less standard SOP for creating content with lessons. Can be followed up on a per-lesson basis.
