### ISSUE TITLE
md5sum on Cavatica

### ISSUE THREAD

**Issue by abhijna** [nih-cfde/training-and-engagement#289]
Thoughts from @s-canchi 

This is tricky indeed not just for this tutorial but for data in general. So I think of two ways to get this information in Cavatica.

- Approach one would be verify the md5sum of the files on AWS after download from osf and add the md5sum as a metadata point for the downloaded file to show in the Cavatica interface. This however assumes that the data file integrity is sustained during the upload from AWS to Cavatica.

- Approach two is to create a CLI in Cavatica using interactive analysis option and to run the md5sum on the downloaded files. I tested this approach and it works. The negative with this approach is that it involves further explanation of steps to set up the interactive analysis.

**Comment by jeremywalter** [comment]
outdated
