### ISSUE TITLE
Home Page improvements: carousel box resize and autoplay

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/training-and-engagement#297]
- [x] The home page has a carousel feature. However on page screens , it does not resize and there is white space on the right. We want it to resize to browser to reduce white space. 

- [ ]  The images and text in the carousel are static. We want to be able to have autoplay with clickable text/image. 

- [x] The bottom boxes all have different sizes. It would be good to have them all be equal size and be symmetrical with different browser window sizes.

**Comment by ACharbonneau** [comment]
I'm pretty sure the [bootstrap carousel](https://getbootstrap.com/docs/4.3/components/carousel/) should address these issues, since our website is ultimately a bootstrap theme and should understand it.

**Comment by s-canchi** [comment]
I tried the Bootstrap carousel previously, but cannot figure out how to use it without overriding the default theme specs. If anyone knows how please share!

**Comment by s-canchi** [comment]
Fixed two of the three in February release.

**Comment by jeremywalter** [comment]
this feature seems stable for now
