### ISSUE TITLE
Add announcement widget and streamline workshop details on home page

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/training-and-engagement#298]
Currently we manually add the past workshop details to the page. We need to be able to create an additional document to source it from.

Or the best outcome would be to add a widget for automatic content update so as to avoid PR based updates to workshop details.

**Comment by s-canchi** [comment]
Currently have linked the events calendar to the homepage but we want to be able to add a widget.

**Comment by jeremywalter** [comment]
something to revisit if desired
