### ISSUE TITLE
Website left navigation panel 

### ISSUE THREAD

**Issue by abhijna** [nih-cfde/training-and-engagement#305]
The left navigation bar for the website is pretty clunky. When you expand multiple tabs, it jumps around a little bit and it is easy to lose track of which tab one was on. @jeremywalter brought this up a few months ago and I've just fully understood the problem.

**Comment by marisalim** [comment]
is part of the problem long titles that wrap onto 2 lines in the nav bar?

**Comment by abhijna** [comment]
Long titles don't help, but I don't think that's necessarily it. As we add more stuff, these nav bars are getting really long and there's just a lot of text if you have multiple tabs open. I think there might be a better way to orient the user about where they are in the nav tree.

**Comment by abhijna** [comment]
hmm.. the solution may be as simple as highlighting the page (on the left nav bar) that one is currently viewing

**Comment by s-canchi** [comment]
Can you screenshot this ? Currently the title of currently viewed page is highlighted in blue in the left nav bar.

**Comment by jeremywalter** [comment]
rayna has been addressing some of this...
