### ISSUE TITLE
All Hands PI meeting

### ISSUE THREAD

**Issue by josesanchez1815** [nih-cfde/training-and-engagement#309]
This Issue is here for us to check for all of the PI's availability within April/May for a meeting. @ACharbonneau 
We want to make sure that we don't schedule this meeting with other big CP meetings, holidays, etc.

**Comment by ACharbonneau** [comment]
Not 
- first week of June
-  week of June 21st
- april 15 or 16
- NCPI meeting May 3-4
- BioData Catalyst quarterly June 2-3
- May: 6-7, 10, 24
- June: 3-4, 14, 24-25.

**Comment by ACharbonneau** [comment]
Not:

NCPI meeting May 3-4
BioData Catalyst quarterly June 2-3

**Comment by mattrBCM** [comment]
Can you clarify: how long is this PI meeting - 1 hr, half day? Is it for PIs only, or can say, the project manager attend?

**Comment by ACharbonneau** [comment]
As soon as we have an actual plan we'll send out that kind of info :)

**Comment by ACharbonneau** [comment]
@jeremywalter could you update this issue please

**Comment by jeremywalter** [comment]
Posted in CFDE Announcements 02-22
Invitations deployed via CFDE mailing list and Cross-Pollination mailing list

CFDE Program Meeting
A major CFDE Program meeting is scheduled for May 10-11, 2021 with presentations and activities taking place from 11am EST until 4pm EST (8am-1pm PST) on both days. All CFDE participants are encouraged to attend two days of workshops and talks on a range of topics. A calendar invitation has already gone out. If you have questions or concerns about his important meeting, contact us at support@cfde.atlassian.net

**Comment by s-canchi** [comment]
This event was successfully conducted virtually.
