### ISSUE TITLE
Deriva API/Python SDK Testing

### ISSUE THREAD

**Issue by josesanchez1815** [nih-cfde/training-and-engagement#311]
Need tutorials about deriva API/Python SDK. 

Someone might want to use an API to access the portal or might want to use the python SDK to access it programatically

[Link](https://docs.derivacloud.org/deriva-py/index.html)

**Comment by ACharbonneau** [comment]
Not quite. You definitely don't need to use an API to use the portal. The portal has a UI. Someone *might* want to use an API to access the portal or *might* want to use the python SDK to access it programatically. So, if the API/SDK seem useful, we could think about writing tutorials for them in the future.

**Comment by jeremywalter** [comment]
rayna can assess/close?

**Comment by raynamharris** [comment]
I am very unfamiliar with concepts in this issue. re-assigned to @ctb and @ACharbonneau
