### ISSUE TITLE
Highlight all levels in left side navigation and disable all tabs feature

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/training-and-engagement#320]
Currently we use MkDocs-material theme for the training website. We have nested tutorial structure which can be lost in the left side TOC. Only the selected lesson is highlighted in light blue shade. What we would prefer is for all the top level folders to be highlighted so as to keep track of lesson origin even when the tab is collapsed. 

Screenshot below highlights the issue:

![Screen Shot 2021-01-29 at 3 58 41 PM](https://user-images.githubusercontent.com/36385305/106342847-6d475400-6257-11eb-8f4c-0b4edcabb2b6.png)

Recent update to the mkdocs-material implements changes the behavior of the `navigation.tabs` feature which now shows all the tabs on all pages. This is not desirable and we want to only have the lessons in the left side TOC for each selected tab. 

Older version (mkdocs-material <=6.1.7)

![Screen Shot 2021-01-29 at 4 35 06 PM](https://user-images.githubusercontent.com/36385305/106342911-b1d2ef80-6257-11eb-95b4-5513bda84b6c.png)

Newer version (MkDocs-material >= 6.2.0)

![Screen Shot 2021-01-29 at 4 36 35 PM](https://user-images.githubusercontent.com/36385305/106342924-c0b9a200-6257-11eb-863c-094d38e93a28.png)

I have also posted the later issue in the [discussion forum in mkdocs-material repo](https://github.com/squidfunk/mkdocs-material/discussions/2257). We want to explore fixes to both issues using some css/html/javacsript tricks. @ctb @ACharbonneau for some help/guidance.

**Comment by s-canchi** [comment]
Related to #305

**Comment by s-canchi** [comment]
The all tab render issue will be fixed in Feb release. It stemmed from a conflict coming from a using the custom partial nav file.

**Comment by jeremywalter** [comment]
done
