### ISSUE TITLE
How to Encourage Zoom Meeting Participation

### ISSUE THREAD

**Issue by josesanchez1815** [nih-cfde/training-and-engagement#333]
We want to use this as a place to store ideas people have tried or want to try to encourage zoom meeting participation.
For @josesanchez1815, it would be awesome to see other participant's videos. If we can encourage people to turn on their videos for a full meeting, that would be a grand accomplishment!

**Comment by s-canchi** [comment]
- Ice breaker topics/games
- alternative site for engaging (google docs/slack/etherpad etc)
- stretch breaks 
- zoom chat consensus building

**Comment by marisalim** [comment]
[EasyRetro](https://easyretro.io/) (previously called FunRetro) for brainstorming

**Comment by marisalim** [comment]
Google Jamboards

**Comment by jeremywalter** [comment]
An ongoing discussion... participation ends up relying on the willingness of the presenter to try and force people to interact. Tools such as those above offer different ways for people to contribute most anonymously.
