### ISSUE TITLE
Selenium Files for Use Case Testing

### ISSUE THREAD

**Issue by josesanchez1815** [nih-cfde/training-and-engagement#338]
So Far I have use case 1,6 and working on 10. Goal is to be able to go through as many use cases as possible throughout the week.
Process Workflow: I go through the use cases and fill out these form templates to the best of my ability that Amanda created for use case testing. As I go through it once and become familiar with the staging CFDE Portal, then I run through the tasks I performed again, but this time with Selenium IDE.

https://github.com/nih-cfde/selenium-test-case

Use Case 1 hackmd: https://hackmd.io/src-seiVTwaNcgcGXmuizQ
Use Case 6 hackmd: https://hackmd.io/jPIdMIcfTn2Z28ayw3fSmA
Use Case 10 hackmd: https://hackmd.io/7CM9p-kMTyi8ts3JPflhxw

**Comment by ctb** [comment]
thanks, jose!

it looks like you have to be logged in to start with, which is good to specify :). I haven't been able to run the first use case myself, it fails at step 8. Could you detail what kind of setup & preparation you need to do?

**Comment by ACharbonneau** [comment]
I haven't looked at these at all, but you should only need to login for 10.

**Comment by josesanchez1815** [comment]
@ctb @ACharbonneau 

Hi! Ok I think I didn't follow directions as I logged into the portal with jsanchez1815@gmail.com for Use Case 1 and 6. I can redo the use cases without logging in.

@ctb I will document my setup a little better.

**Comment by josesanchez1815** [comment]
[Use Cases_nih_cfde_2.zip](https://github.com/nih-cfde/training-and-engagement/files/6038323/Use.Cases_nih_cfde_2.zip)

Some important things to note. I need to redo the use case 6 and use case 10. I had some difficulty using the selenium software. I am confident you will be able to run use case 1.

**Starting page** : https://app-staging.nih-cfde.org/
**Browser:** Google Chrome

When Running Use Case 1, you do not need to log in.
I cleared my cache and google history (I'm not sure if that is necessary in this case)

## Important steps to take when using Selenium IDE for this use case

When the program pauses for the first time, we need to click on "Search all collections"

![usecase1_search_all_collections](https://user-images.githubusercontent.com/62918474/109055331-e473da80-7693-11eb-8b0b-3b2ecc4478b4.PNG)

When the program pauses for a second time, we need to scroll down to the section that says "Contained Biosample" and click on the Explore Button on the far right of the screen.

![usecase1_ explore button](https://user-images.githubusercontent.com/62918474/109054107-59461500-7692-11eb-91e6-b49d715eed07.PNG)

**Comment by josesanchez1815** [comment]
Something I have yet to figure out, is if I can automate the clicking of the Search all collections button and explore button. I am sure there is. otherwise the program pauses until I manually click those buttons.

**Comment by ctb** [comment]
right now it's getting stuck on "click on id=search collections"

would it be possible for you to give me a short video of you going through it, perhaps with some narrations? you can just start up a zoom and screen share and record to cloud, and then send me that link. I just don't know how to debug it right now.

**Comment by josesanchez1815** [comment]
That does sound like a better idea. Sure!

________________________________

**Comment by ACharbonneau** [comment]
So, I have a hot take about [this comment](https://github.com/nih-cfde/training-and-engagement/issues/338#issuecomment-785320195) which is that if this is for use case 1, there is no reason to go to contained biosample or click explore. 

To do this use case you would:

- go here https://app-staging.nih-cfde.org/ (technically https://app.nih-cfde.org/ but staging is the testing server)
- click on collections (or any of the 'view data by' options, it doesn't actually matter)
- in the anatomy sidebar either search for 'brain' in the search at the top of the anatomy box or choose 'show more' search by brain in the pop up and select "all on page" to check them all or manually check them all. All 3 ways give you the same 11 tissues so it literally doesn't matter
- in the assay sidebar, same thing as anatomy except you want "rna" and there's 2 matches

...and then the use case breaks because HuBMAP did not put in data yet, and we didn't add disease terms so you can't possibly search by disease.

- then you click 'export'. Depending on which way you decided to search, you either get 11,477 biosamples, 2,582 files or one collection

**Comment by ctb** [comment]
my own hot take: would prefer something that works, end to end, over refinement for a specific use case (for the moment).

**Comment by s-canchi** [comment]
I was trying selenium for use case 7 and got it to work for the first half but it gets stuck in the second half where we clear the search bar to type a new search criterion. The process was without logging into the portal/interface.

I will redo the test to include both search criterion at the same time in the search bar to see if that works and share the test file if successful :)

**Comment by josesanchez1815** [comment]
https://user-images.githubusercontent.com/62918474/109073494-4db31800-76ab-11eb-9ce6-2e4f6bb82fdf.mp4

**Comment by josesanchez1815** [comment]
I will need someone else to test it, but use case 6 should be useful for a demo. Still working on fixing up use case 1 to be useable as I have to manually click on buttons for the selenium program to keep on running.

**Comment by s-canchi** [comment]
I ran the @ctb edited version of the use case 6 but ran into the same problems that I previously saw when I was testing uc007.
https://www.loom.com/share/c8ebb2732f71470ca3a57f33f6eb3939

p.s - I forgot to turn off the microphone for this, so ensure to mute the video for the static noise.

**Comment by josesanchez1815** [comment]
I have uploaded Use Case 1 and Use Case 6 here https://github.com/nih-cfde/selenium-test-case

**Comment by jeremywalter** [comment]
Do we want to do more work here where Jose left off? Was it valuable? Can this be closed?

**Comment by jeremywalter** [comment]
can be re-opened if needed
