### ISSUE TITLE
Website reorg to improve navigation

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/training-and-engagement#344]
With most of the new lessons focussed on the Bioinformatics tab, it currently become very heavy for the left side TOC. We want to reorg the website to spread out the lessons in their own headers and remove unused headers (web development --> CFDE internal) and create a new tab for DCC content.

**Comment by josesanchez1815** [comment]
I'm not sure if this issue is the proper place to put this, but I just wanted to share my interest in this particular set up. So I recently went to the [DISCORD support page](https://support.discord.com/hc/en-us) and like how the information is organized. We may not be able to do this anytime soon (I'm not sure how long something like this would take), but I think this would be really cool for our CFDE Training Site. It could help simplify where people could look for support in Jira.

https://support.discord.com/hc/en-us
![image](https://user-images.githubusercontent.com/62918474/111509782-5034ea80-870a-11eb-9bd3-6885412dde92.png)
 @s-canchi @abhijna @marisalim @jeremywalter @ACharbonneau @ctb

**Comment by josesanchez1815** [comment]
Or at the very least maybe we can create a support tab and in that support tab we can create a place for people to submit their issues to the proper jira help desk.


CFDE Portal Website could benefit from a support page too! It may help us reduce issues like people responding to the wrong jira address.

**Comment by s-canchi** [comment]
These are some good points @josesanchez1815 ! There is a way to add categories in the CFDE helpdesk portal and we had experimented with those. However, I remember that we decided to shift the category burden to the helpdesk and not to the user. So for now we have only one form for users to submit tickets but we triage and categorize it internally. if you notice our helpdesk has multiple queues of different categories for this exact reason.  

We already have the helpdesk email in our training website. The one thing we have not tried yet is the jira widget which would allow the user to submit a form (similar to the one from the CFDE helpdesk portal) from the training website. I can't remember why we haven't used the widget. 

But I do however like the idea of content boxes as a visual way to direct a user instead of using header tabs. I am not sure of exact implementation either though but might be worth a try!

**Comment by josesanchez1815** [comment]
I see. I do remember us talking about shifting the category burden to the help desk. Thanks Saranya.

**Comment by marisalim** [comment]
discussed today --

- [x] move CFDE Internal (except style guide) to nih-cfde website. This is the basic theme the nih-cfde website uses if you'd like to see the possible page layouts: https://aardvark.ghostpool.com/elearn/ --> lives here now https://www.nih-cfde.org/resource/overview/
- [x] have style guide not render on the website - will happen on #356 
- [ ] make a tab for CF tools and move KF/CFDE portal lessons there
- [ ] split the Bioinformatics Skills into 2 tabs - one for the software environment/cloud platform stuff (i.e., AWS, GCP, conda, Terra, snakemake) and another for the bioinf analyses stuff (i.e., GWAS, blast, RNAseq, sim illumina reads)

**Comment by marisalim** [comment]
Ideas on new navbar names? 

Currently we have:

Home | Bioinformatics Skills | Cheat Sheets | Web Development | CFDE Internal Training | Release Notes
 --- | --- |  --- |    --- |    --- |    --- |      


Considering for reorg - topics, but these names are maybe too long:

Home |  General Tools | Cloud Platforms  | Bioinformatic Analyses | Common Fund Tools  |  Release Notes
 --- | --- |  --- |    --- |    --- |    --- |   
unchanged | snakemake, (adding conda for May; binders), Web development could move here; Cheat Sheets could move here| AWS, GCP, (adding Terra for May), Cavatica | GWAS, blast, RNAseq, sim Illumina reads | KF, CFDE portal (adding fairshake, hubmap RUI for May) | unchanged


@nih-cfde/training please add suggestions here! we will finalize at our next meeting :)

**Comment by s-canchi** [comment]
I like the new headers! All the headers are to the point. I would only shorten the cloud computing one:

Cloud computing & workflows --> cloud computing 

Would it be weird to retain the web development tab ?

**Comment by marisalim** [comment]
i guess we could, but we aren't actively adding to it, so seems to be taking up navbar real estate 😅

**Comment by josesanchez1815** [comment]
Yeah I think the web development tab is not so necessary. But that's my opinion.

I would even take out the cheat sheets tab and include them in their respective tutorial web pages.

**Comment by marisalim** [comment]
new suggestions on https://github.com/nih-cfde/training-and-engagement/issues/344#issuecomment-807536563

**Comment by marisalim** [comment]
order: home, CF tools, cloud, bioinf analysis, gen tools, release notes

link multiple lessons - i.e. GWAS in the cloud could go in bioinf analysis and cloud
