### ISSUE TITLE
Onboard DCC Individuals to Globus groups

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#345]
I need to onboard at least submitters and approvers for:

- [x] Kids First
- [x] GTEx
- [x] LINCS
- [x] IDG
- [ ] SPARC
- [x] HuBMAP
- [x] HMP
- [x] ExRNA
- [x] Metabolomics

And maybe also for:

- [ ] MoTrPAC
- [x] 4DN

So they can start using the system.

**Comment by ACharbonneau** [comment]
As a DCC you have 3 role options for users of the submission system:
- Reviewer: Basically read only. They can see submitted packages, but can’t do anything with them. You can have as many of these as you want.
- Submitter: Can submit data packages, but can’t approve a package for inclusion in the pubic portal. You can have as many of these as you want.
- Approver: Can approve a submitted package to be published to the CFDE portal, but can’t submit new packages. Each DCC has one person who is the final approver.

Any given person in your org can have 0-3 roles. If they have 0, then they can only see the published data, so exactly the same as any user of the portal. If they have one or more of the other roles, they get those privileges. Privileges stack. So if one person needs to submit packages and is the final approver, then they have both roles.  

We’re still working out how we will administer roles long term in practice, but if you know who you would want administering those roles long term, you can tell me that too. For the moment, @ACharbonneau is acting as admin on all of them until we’re sure the system is working.

To do the onboarding, for each person I really just need:
- [their Globus display name](https://github.com/nih-cfde/security/blob/master/epic-1-groups/dcc-instructions.md)
- what role(s) you want them to have

**Comment by ACharbonneau** [comment]
Enrolled 4 people for HuBMAP from Kevin Hanshaw email

**Comment by ACharbonneau** [comment]
Enrolled 7 people for LINCS from Sherry Jenkins email

**Comment by jeremywalter** [comment]
Removed Erin Friday from HMP Reviewers.
Added Sherry Jenkins to LINCS Reviewers.

**Comment by jeremywalter** [comment]
https://github.com/nih-cfde/published-documentation/issues/177#event-4438913895

**Comment by ACharbonneau** [comment]
We're still on boarding as needed, but have a workflow, tracking system, and wiki page so closing
