### ISSUE TITLE
Onboarding system for Submission

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#347]
We now have basic instructions here: https://github.com/nih-cfde/published-documentation/wiki/Onboarding-to-the-CFDE-Portal-Submission-System

@jeremywalter  We still need:

- [ ]  A submission system [associated github issue](https://github.com/nih-cfde/training-and-engagement/issues/345)
- [ ] an updated process document for the onboarding team to follow when adding/removing people [original version is here](https://github.com/nih-cfde/security/blob/master/epic-1-groups/epic-1-groups.md)

**Comment by jeremywalter** [comment]
Form for entering onboarding info:
https://forms.gle/cXxSVKT2epGr4otZ9 
Form spreadsheet (restricted) - Amanda/Jeremy
https://docs.google.com/spreadsheets/d/1UpVcIdM5B-vrK_P3VWkNGGS2IQLJCDT2_DoKNht7AuM/edit?usp=sharing  <-- all submission tracking is happening here for now

**Comment by josesanchez1815** [comment]
Thanks Jeremy!
________________________________

**Comment by ACharbonneau** [comment]
The PM or PI fills out the form for everyone on their team. I don't want people signing themselves up as authorized

**Comment by ACharbonneau** [comment]
I think you should probably talk to @kloydrti about rolling this in as another type of onboarding in the private site so that we can restrict who can do it

**Comment by jeremywalter** [comment]
The reason I made the form (for better or worse) is for us to enter the info for tracking. Potentially PIs could be asked to fill it in (been thinking about this) but the responses would ultimately be vetted by admins who can see the results OR the admins would use the form themselves.  I'm trying to make something easier for tracking and managing than markdown tables. I found that I can manipulate the spreadsheet (delete and re-order) without breaking it so it seems like it could be useful.

--Note, it also seems to allow me to add manually to the spreadsheet if I get handfuls of people to process at one time -- so far I haven't gotten it to break

**Comment by ACharbonneau** [comment]
but we already have restricted access onboarding set up in the website, so it seems like it would be easier on everyone if they only had one onboarding form

**Comment by jeremywalter** [comment]
https://github.com/nih-cfde/private-website-content/issues/6

**Comment by kloydrti** [comment]
If you want to allow PIs to fill in a form similar to the onboarding form on nih-cfde.org, I can set that up. The page would be restricted to users who are designated as PIs / PMs. The forms plugin has an integration with Google Sheets, so we could send all of the form submissions to one place (they would also be saved in the WordPress database).

**Comment by ACharbonneau** [comment]
I think we might just literally need to add 3 checkboxes and a ID collection box to the existing form:

Onboard to submission as: 
- [ ] Reviewer
- [ ] Submitter
- [ ] Approver

and 

What is the users Globus ID? _______________

**Comment by kloydrti** [comment]
Are either of these questions required to submit the form? Do they only need to appear on the form for onboarding to "all CFDE sites" (as opposed to just the nih-cfde.org site)?

**Comment by ACharbonneau** [comment]
just on the "all CFDE sites" form. and not required.

**Comment by jeremywalter** [comment]
So for people to onboard for submission they have to go to onboarding and click on 'all CFDE sites'? I think this could be confusing (it confuses me). If I'm trying to get people onboarded for DCC submission it's not the same as onboarding to the CFDE and it's not for 'all CFDE sites'. Shouldn't this be a separate (third?) choice on the onboarding screen? Perhaps I'm missing part of the plot here.

**Comment by ACharbonneau** [comment]
You might have a point. Maybe it should be a separate onboarding function from all the sites.

**Comment by ACharbonneau** [comment]
It should still be in the private site and have those options, but it's own form

**Comment by ACharbonneau** [comment]
The real question is whether you need to be regular onboarded to do a submission to the portal. And you do not. DCCs can add data without being funded. So we should have formed in the website for: regular onboarding, submission system onboarding, and just the private site onboarding

**Comment by ACharbonneau** [comment]
documentation to include in onboarding docs https://github.com/nih-cfde/security/issues/15

**Comment by jeremywalter** [comment]
I can't tell if there is anything else to be done here. Related issues and documentation seem to exist.

**Comment by jeremywalter** [comment]
Need the offboarding side

**Comment by jeremywalter** [comment]
Done: https://github.com/nih-cfde/published-documentation/wiki/Offboarding-from-the-CFDE-Portal-Submission-System
