### ISSUE TITLE
privacy policy

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#349]
Help develop the privacy policy for the personalized portal and review with DCCs

**Comment by ACharbonneau** [comment]
We need a privacy policy to have people agree to when they sign up to use the portal. I'm not sure what needs to go in there. Any ideas @ctb ? Or is this a thing that UMD lawyers might have to do @RLC-DCPPC ?

**Comment by karlcz** [comment]
We also need to determine each place we will provide a link to the policy.
- in the new group registration page
- in a navbar menu (perhaps User Help -> Privacy Policy?)

**Comment by ACharbonneau** [comment]
I made a preview of the render: https://docs.nih-cfde.org/en/preview/about/privacy/

Currently waiting for Rick to look at it. 

PR that would make it appear in live site: https://github.com/nih-cfde/published-documentation/pull/251

Address that we would link to from the portal to get it: https://docs.nih-cfde.org/en/latest/about/privacy/

**Comment by ACharbonneau** [comment]
Currently the link is broken, because the PR hasn't been merged. BUT that URL is stable, so you could add it into the portal or whereever now and it will start working when the PR goes through
