### ISSUE TITLE
Update Conda tutorial based on workshop experience

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/training-and-engagement#350]
We can enhance our current conda lesson based on the pilot workshops. 
As @jeremywalter pointed out, the Step 2 in our current conda lesson does not provide enough context and should be rectified. We can add some thing like : `Let’s check our installation to make sure it went smoothly. We can do this by verifying the digital fingerprint or ‘hash’ of the files we just installed.` to this step for clarity.  The updates will be made for the May release.

**Comment by marisalim** [comment]
this will include update on our macOS conda install lesson + adding material based on intro to conda workshop
