### ISSUE TITLE
Update RNAseq tutorial 

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/training-and-engagement#352]
- [x] In the Cavatica-view.. lesson, in Step 2, there is an error in total files as it mentions 98 but should be 99. 
- [x] In the setup DESeq2 app, the GTF file should be v27 gencode and linked to the GitHub page for the KFDRC rnaseq pipeline that shows the suggested inputs. 
- [x] Update the vidlet for Obtaining reference gene annotation
- [x] Update vidlets and analysis reports in the Analysis with DESeq2 Public App
- [x] Update the script in Analysis with Data Cruncher to read the new GTF file.

**Comment by marisalim** [comment]
- [x] fix images that aren't rendering, i.e., here: https://github.com/nih-cfde/training-and-engagement/blob/dev/docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna_seq_3.md
- [x] also #463
