### ISSUE TITLE
add workshop FAQs

### ISSUE THREAD

**Issue by marisalim** [nih-cfde/training-and-engagement#359]
add to the [Discussions section](https://github.com/nih-cfde/training-and-engagement/discussions) of this repo

- from Conda workshops: https://hackmd.io/RweX2WZ7RGGtfLfCDuEubQ

**Comment by s-canchi** [comment]
All conda workshop questions have been added.

**Comment by marisalim** [comment]
AWS Q&As were added. closing issue, continue adding Q&As to the Discussion board as the come up!
