### ISSUE TITLE
Update CFDE Portal tutorial 

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/training-and-engagement#374]
The CFDE Portal will be publicly launched end of March 2021. The CFDE Portal tutorial on the website used the older version of the data. The lesson along with the videos and screenshots have to be updated to match the latest data and UX of the portal. Timelines:

- CFDE Pop up demo on April 14th
- Website Release in May 2021.

(update: these lessons have a lesson in development banner as of the June 2021 release)

**Comment by ACharbonneau** [comment]
Is this done??

**Comment by s-canchi** [comment]
Unfortunately it is not complete. Previously, there was no actual data the first time around and the underlying data changed with second iteration. So some of the searches did not work. Is the current data in portal set to remain unchanged with future iterations ?

**Comment by ACharbonneau** [comment]
The portal data is always changing, it will never be set. That's the whole idea, it's an always up to date resource. We can't not do training just because the data changes, trainings are just going to have to deal the way the portal works.
