### ISSUE TITLE
FAIRshake documentation

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#38]
The Ma'ayan team has been producing all sorts of FAIR metrics and has made several tools/scripts for doing the assessment. There is a repo here: https://github.com/nih-cfde/FAIR
and some of the results here: https://fairshake.cloud/project/87/

What I haven't been able to find is documentation that would help a DCC understand their rating, or how it came to be. Within FAIRshake, with enough clicking I can get to pages like this: https://fairshake.cloud/metric/108/ that will tell me a definition for a specific metric, but its not very easy to get to. They also have a documentation page: https://fairshake.cloud/documentation/ which has some tutorials, but mostly it is technical spec sorts of information.

One thing we heard on our site visits (from 4DN specifically) was that we gave them FAIR scores, but that they couldn't figure out why they got the score they did. We want to make sure that we're being transparent about our criteria, in a way the DCCs can understand and use. For instance, one question in FAIRshake is "The structure of the repository permits efficient discovery of data and metadata by end users". That could be accomplished in a lot of ways, and what is efficient to me might not be efficient for everyone...If I'm a DCC that gets a low score, what am I supposed to do to improve it? How am I supposed to understand that information?

What I'd like, is to work with @nih-cfde/ma-ayan group to make documentation for FAIRshake that is aimed at DCCs. Right now, it's all aimed at developers or people doing scoring, and those are good to have, but as a DCC, I don't want to watch 20 videos about how to physically do scoring to find out how scoring applies to my data. This documentation should answer questions like:

How does FAIRshake evaluate interoperability?
How can I increase a specific FAIR score?
How do I read/understand this colored box thing?
How do I dispute/correct/change/question my FAIR rating?

**Comment by swandle06** [comment]
Just to update a little further, the documentation we developed last December is here:  https://docs.google.com/document/d/1i3DUYGve8Ff0H8qcLR3wjp3-vOOocXt1-rH1S1oPLT8/edit?folder=1Ur-btky6Gu2ZP-WIUl8jCdFfyWk2F-zQ#heading=h.46zx3yjsmmsh. Based on the recent communications on Slack, we're planning to merge this effort with the ongoing efforts here:  https://github.com/nih-cfde/the-fair-cookbook. We'll provide additional updates here as the work progresses.

**Comment by ACharbonneau** [comment]
https://github.com/nih-cfde/deliverables/issues/69

**Comment by dcfcjcheadle** [comment]
The FAIRshake rubric document, which was created to address this request, has been converted to markdown and added to the FAIR Cookbook repo.  @ACharbonneau, is it reasonable to close this issue and document any cookbook content additions in nih-cfde/deliverables#69?

**Comment by ACharbonneau** [comment]
I haven't been following the fair cookbook stuff, but my main concern would be whether it actually is filling the role I'm looking for here. My (perhaps wrong) belief about the cookbook is that it is about how to do things...how to do an assessment, how to run a thing...so instructions, like a standard cookbook. 

What I am looking for here is a guide for people who want to understand FAIRshake, not people who want to run it.

**Comment by u8sand** [comment]
@ACharbonneau to what extent might [this recently made cookbook](https://github.com/nih-cfde/the-fair-cookbook/blob/c1da35789e7aff4a89ec27fa41c05cc222c26738/content/recipes/04/fairshake.md) address what it is that you're looking for?

**Comment by AviMaayan** [comment]
There is also the paper: https://www.cell.com/cell-systems/fulltext/S2405-4712(19)30345-X
