### ISSUE TITLE
DEseq2 corrections

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#392]
>  Although, using LFC shrinkage does not impact the total number of genes that are identified as being significantly differentially expressed, it is useful for downstream assessment of results. 

This isn't true. The shrinkage parameter changes both the number and identities of DE genes. Being able to substantially change the results by shrinking the LFC is pretty much the only reason to use DEseq2 instead of another DE algorithm.

**Comment by s-canchi** [comment]
Can you explain this ? I found this explanation about lfcshrink() from Michael Love:

>  While for the majority of bulk RNA-seq experiments, the LFC shrinkage did not affect statistical testing, DESeq2 has become used as an inference engine by a wider community, and certain sequencing datasets show better performance with the testing separated from the use of the LFC prior.
> The shrunken fold changes are useful for ranking genes by effect size and for visualization.

Relevant posts: 
- https://support.bioconductor.org/p/77461/#107693
- https://support.bioconductor.org/p/95695/

I ran the DESeq2 app on the selected dataset with and without the lfcshrink and find 1580 more genes with lfc on and the padj value are slightly more significant with lfcshrink.

**Comment by ACharbonneau** [comment]
The quote is about a technical change in where in the code the LFC shrinkage is happening. It used to happen as part of the main call, and now it's a separate function that is called by the main call. Most end users will never, ever, notice the difference, but for a tiny subset of users, having the LFC call be technically freestanding allows you to tinker with the how effect sizes are calculated without breaking the LFC shrinkage.

**Comment by ACharbonneau** [comment]
You would expect that if you run with and without lfcshrink you will get very, very different results. That's why I objected to this part of the lesson in the first place. If you go to day two of the RNAseq lesson I taught a few weeks ago, there's an extremely through explanation of the difference.
