### ISSUE TITLE
IG formal interviews with POs

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#4]
Milestone for https://github.com/nih-cfde/cfde-deriva/issues/10

- [x] Double check IG times/dates
- [x] Book ~8 POs
- [x] Confirm 'exit interviewers'
- [x] Distribute watch information
- [x] Distribute recordings/reports

**Comment by ACharbonneau** [comment]
Meeting was scheduled 4/29. Got cancelled. Waiting for re-schedule

**Comment by ACharbonneau** [comment]
IG: `June 3 - 5 or June 10 - 12 as test dates for the Program Officers. After that, we’d not be available again for testing until July 1 - 3. Time slots for the eight users would be: 9amPT (12pmET), 11amPT (2pmET), and 1pm PT (4pmET) regardless.`

**Comment by ACharbonneau** [comment]
> Hello everyone,
> 
> We'd like to interview some volunteers about our portal user interface. This is a chance to tell us how you would like to review data from your DCC program(s) and to help us correct course on anything we’ve gotten wrong.
> 
> If you are available and interested in being interviewed, please respond to this email with your preferred date and time. Appointments for interview sessions are available on June 3rd, 4th, and 5th at noon, 2pm and 4pm each day.
> 
> Details:
> 
> As you may recall from the Common Fund Data Ecosystem Kickoff meeting in January, the CFDE-Coordination Center is working to create a centralized portal for accessing data from Common Fund Programs. This portal will provide both an interface for end users to find new data, and an interface for NIH Program Officers, Managers and Directors to see information about the data curated by their Programs. We have contracted a professional user interface design company, Interface Guru, to do a third party assessment of our tools and design, and are looking for approximately eight volunteers to participate in their assessment of the NIH interface. 
> 
> Each volunteer would participate in their own, approximately 1 hour long session with Interface Guru via video conference. During the session, you would be able to explore the current interface and tools, and to provide suggestions for new or different features.
> 
> If you have any questions please let me know, and thank you in advance for your participation,

**Comment by ACharbonneau** [comment]
so far have 2 scheduled. Sent out email with new dates today

**Comment by jeremywalter** [comment]
**Confirmed with PO and Zoe**
Name | Date | Time
--- | --- | ---
Lora | June 3 | 4pm
Sean Hanlon | June 5 | 2pm
-- | June 11 | 2pm
-- | June 11 | 4pm
-- | June 12 | 2pm
-- | June 12 | 4pm
