### ISSUE TITLE
home page updates

### ISSUE THREAD

**Issue by marisalim** [nih-cfde/training-and-engagement#401]
- [ ] reminder to add the new workshops to home page from April/May

**Comment by marisalim** [comment]
- [ ] reminder - after the next release, the navbar reorg is going to result in broken links from i.e. workshop note links to AWS (which will be moved from "Bioinformatic Skills" to "Cloud Platforms"). make sure this is highlighted in release notes, could also be noted on home page?

**Comment by josesanchez1815** [comment]
I think we may want to consider change the wording in this post in future web updates. When I first read this list, I get the impression that the workshops are supposed to be upcoming workshops and not workshops we have done in the past.  A simple rewording like "Check out these materials from past workshops!" or "Did you miss any of our past workshops? Check out the materials here!"
![image](https://user-images.githubusercontent.com/62918474/115915060-9f67ec80-a427-11eb-8124-7823206cb600.png)

**Comment by s-canchi** [comment]
Thats a good point @josesanchez1815. Hopefully replacing this section with the calendar might help avoid these issues.
