### ISSUE TITLE
LINCS training materials

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#42]
LINCS already has materials for a graduate-level course called “Data Science with LINCS Data” that they would like to offer publicly. Each lecture has a Jupyter notebook, PowerPoint slides and lecture notes. However, these resources need some work to be offered as a MOOC.

Basic Process:
-  @nih-cfde/lincs will send us the materials they have (via @sherry-jenkins)
- one or more members of @nih-cfde/training will review content and offer feedback 
- @nih-cfde/training will help improve content as necessary
- @nih-cfde/lincs will record the videos
- @nih-cfde/coordinators will help edit videos

Ideally, this will happen in rotating stages, such that there is always one lesson being reviewed, one being improved, one in process of filming, and one in video editing until we get through all of them.

https://github.com/nih-cfde/deliverables/issues/89

**Comment by AviMaayan** [comment]
This sounds like a great plan. Thank you @ACharbonneau!

**Comment by abhijna** [comment]
Hi @sherry-jenkins I have time to start reviewing materials if you send them. Please put them here: [LINCS MOOC google drive](https://drive.google.com/drive/u/1/folders/1W8UEY9D05i6-k3VIxvrXLweVZmqty4ao) or post links here :)

**Comment by ACharbonneau** [comment]
LINCS dropped this from their deliverables. 

@ACharbonneau
