### ISSUE TITLE
Update and fix Kids First Training materials

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#43]
An initial set of materials was delivered in https://github.com/nih-cfde/training-and-engagement/issues/14

However, the final stages of the materials are in dis-repair and don't/can't work because of https://github.com/nih-cfde/risks/issues/11

I'm closing that issue and starting this one for updating purposes. 

Will next be part of https://github.com/nih-cfde/deliverables/issues/89

**Comment by ACharbonneau** [comment]
Ideas for changes to current material: Consider moving page [5](https://cfde-training.readthedocs.io/en/latest/KF_5_Explore.html) to after page [2](https://cfde-training.readthedocs.io/en/latest/KF_2_Registration.html). so, taking a break from setup instructions to look at the dashboard. could be less fatiguing, but also might annoy people to have to go back to set up when they thought they finished :/

**Comment by ACharbonneau** [comment]
Risk #11 has been resolved. We should be able to finish writing this tutorial now. I won't have time for a bit, but will come back to it if no one else picks it up.

**Comment by ACharbonneau** [comment]
This is what you're working on @jeremywalter

**Comment by jeremywalter** [comment]
https://github.com/dib-lab/cfde/issues/128
KF Training Walkthrough notes

**Comment by jeremywalter** [comment]
Pre-requisites have the caveat 'preferred' for ORCID and eRA Commons... is it possible to do any of this without them? I would like to deprecate the preferred.

**Comment by abhijna** [comment]
I can't use my ORCHID to log into kidsfirst and so far I have not had a problem

**Comment by ACharbonneau** [comment]
you won't be able to do a protected data analysis without them. NIH does credentials thorough ORCID and eRA

**Comment by jeremywalter** [comment]
I'm just concerned about the context of the lesson... where at minimum you should be able to access, move, and analyze the open data sets. I had not been able to make everything work without both pieces... but it was a pretty messy process the first time through and I don't know if others found a way through without ORCID =and= eraCommons

**Comment by ctb** [comment]
Also, neither of these are burdensome to get. Most biomedical scientists will have eRA credentials, and ORCID is I think pretty straightforward to get (and is also something I want to push!)

Perhaps we could have people enter their ORCID in order to register for our workshop(s).

**Comment by ACharbonneau** [comment]
you should be able to do everything in that lesson without both or either of them. Some of the lesson might be out of date since cavatica has had a couple updates, which is why we need to update/fix it. Regardless, I don't see the problem with telling people which method of auth they should opt for if they have it. Do you just not like the word 'preferred'? Or you don't like that which method you choose changes your future options?

**Comment by jeremywalter** [comment]
I was not able to complete the lesson successfully without both, but it's unclear to me why... there were issues with logging in at one point, and getting access to the data in another... not sure how to recreate the process...

**Comment by ACharbonneau** [comment]
hmm. If you can't recreate it, this is kind of a pointless thing to say now, but I'm gonna say it and put it in the notes for the meeting to say at everyone cause it's important:

For things we're testing, and especially for things that we have absolute control over (like this tutorial) it's really, really important to record your problems and your progress as you have them. We can't fix things in our tutorials, or have other groups fix things that are broken unless we can give a detailed explanation of what the problem is. Yes, it's important to try to work through your problem on your own a bit before asking for help, but you should still be recording what you're doing and why. Abhijna actually did this really well in an issue a few days ago. https://github.com/dib-lab/cfde/issues/141. But it doesn't have to be 'public' I always write a stream of consciousness log in a note app while I'm testing stuff. It doesn't matter how/where you do it, but debugging things requires a step by step record of what you did. 

For something like this, it sounds like the tutorial was really hard for you to follow...which means we should be fixing it to make it easier to follow. It's intended to be a 'work through on your own online' thing. But I don't know what to fix from your description.

**Comment by jeremywalter** [comment]
I have made significant edits to the text and formatting for KF Setting up and Exploring Data sections. I have not found a way to 'fix' the graphics, however. The .png files are good size and resolution, but the style formatting for the website make them appear very small (to appear between the TOC menus). Any thoughts on how these can be improved? @marisalim @s-canchi @abhijna @josesanchez1815 ?

https://cfde-training-and-engagement.readthedocs-hosted.com/en/latest/Kids-First/Exploring-Data-in-the-KF-Portal/KF_6_Filtering/

**Comment by marisalim** [comment]
you could try fiddling with [image size](https://github.com/mkdocs/mkdocs/issues/1678), but it looks like the width is already maxed out, and increasing height stretches the file ... 

alternatively, when i select the image option 'View image', i can zoom in on the png file...

**Comment by abhijna** [comment]
Hmm.. can we make them links so people can click on them to enlarge the image? Didn't they use to do that on one of our websites?
