### ISSUE TITLE
Kids First alternative training

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#44]
Continue the lesson (https://cfde-training.readthedocs.io/en/latest/) further downstream by working with data that already lives on Cavatica to teach WGS and RNASeq 

https://github.com/nih-cfde/deliverables/issues/89

**Comment by jeremywalter** [comment]
tagging @raynamharris to get her input

**Comment by raynamharris** [comment]
There are multiple lessons now using Kids First (see https://cfde-training.readthedocs.io/en/latest/Common-Fund-Tools/Kids-First/ and https://cfde-training.readthedocs.io/en/latest/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna_seq_1/). Seems like we can close this.
