### ISSUE TITLE
update nih-cfde.org with support e-mail address

### ISSUE THREAD

**Issue by ctb** [nih-cfde/training-and-engagement#455]
We should make sure that `support@cfde.atlassian.net` is more clearly present on both nih-cfde.org and app.nih-cfde.org.

**Comment by ACharbonneau** [comment]
@nih-cfde/coordinators

**Comment by ACharbonneau** [comment]
@nih-cfde/coordinators

**Comment by jeremywalter** [comment]
So... nih-cfde.org has a contact button, and it makes the user fill out a bunch of information... and then that info goes... somewhere? I just filled it out and I don't know what happens. Could the Contact sheet just be a link to the support desk instead?
https://www.nih-cfde.org/contact/ -- what happens to contact applications/entries?

**Comment by jacko13** [comment]
Hi @jeremywalter.
At the time a submission is made, the site admin gets an email with the subject "New contact form submission from nih-cfde.org" - showing the submission.  I can investigate exactly who this is.
The submissions are viewable on the Admin side of Word Press. There is a function to view submissions through the WordPress Dashboard. I was able to access and view your most recent submission.
It looks like at one point, we had this integrated to push submissions to a Google Spreadsheet, but that function is no longer activated.
We just added the Contact Us widget - I believe that does log to Jira currently - that widget is only viewable if the user has logged in as a CFDE member.
I'm thinking the value of the current Contact Us page is that it is available to the public and gives someone who isn't a CFDE member a way to reach out for us.
I don't mind brainstorming and chatting to determine if we want to make any changes to this. I'm also happy to dig into the history of this page a bit more as well.

Let me know your thoughts.

**Comment by jeremywalter** [comment]
I think @ACharbonneau will weigh in, but I think having inquiries go to support@cfde.atlassian.net should be fine (for everyone). If the helpdesk gets overwhelmed for any reason we can revert. I'm not very familiar with Wordpress so could not find my entry in the dashboard structure (so many plugins!).

**Comment by raynamharris** [comment]
It's not exactly clear how to accomplish this. 

The [training website](https://training.nih-cfde.org/en/latest/) has a nice banner across the top that says something like "contact us" that was created with some HTML code. 

The [portal](https://app.nih-cfde.org/) and the [homepage](https://nih-cfde.org/) are built with wordpress. Maybe the email can be added in a footer? or separate paragraph?

**Comment by jeremywalter** [comment]
Support e-mails:
- [x] https://training.nih-cfde.org/en/latest/
training helpdesk linked in banner at the top of the page
- [ ] https://app.nih-cfde.org/ --> User Help -> Email the Helpdesk **BROKEN**
- should reorganize User Help to make Helpdesk more prominent 
- [x] https://nih-cfde.org/
support helpdesk linked in About->Contact | Login also offers 'Contact Us' widget

**Comment by raynamharris** [comment]
thanks jeremy! 

regarding the second point, following the "User Help -> Email the Helpdesk" doesn't actually work for me. It opens up a new tab that says "about:blanks" or  "unsafe:mailto:support@cfde.atlassian.net" .

Let me see if i can get someone on the UX team work on this.

**Comment by jeremywalter** [comment]
heh... bad md formatting... I wrote broken up there but I put it in invisible brackets.

**Comment by ctb** [comment]
On Wed, Jun 15, 2022 at 02:13:56PM -0700, Rayna M Harris wrote:
> thanks jeremy! 
> 
> regarding the second point, following the "User Help -> Email the Helpdesk" doesn't actually work for me. It opens up a new tab that says "about:blanks" or  ***@***.***" .

the ***@***.*** is correct.

**Comment by jeremywalter** [comment]
I wanted to check if there is a ticket for the portal maintainers to finish this, but I am not seeing/identifying the right repo
--is there a repo for the portal website?

**Comment by raynamharris** [comment]
probably [nih-cfde/cfde-deriva](https://github.com/nih-cfde/cfde-deriva). see https://github.com/nih-cfde/cfde-deriva/issues/232 for example

**Comment by jeremywalter** [comment]
Created issues over at cfde-deriva for dev team to follow-up:
https://github.com/nih-cfde/cfde-deriva/issues/364

all done here!
