### ISSUE TITLE
add training mailing list link to training site

### ISSUE THREAD

**Issue by jeremywalter** [nih-cfde/training-and-engagement#461]
this could go in the workshop box with a link the training@cfde.atlassian.net for users to request adding to our training mailing list

**Comment by s-canchi** [comment]
Check out the implementation in the recent PR.: https://cfde-training-and-engagement--464.com.readthedocs.build/en/464/

Can we just add the training mailing list email instead ? This can added as a separate icon on top of the home page. The advantage there would be that the info would be available from any page and not just the home page as it is currently. I don't like the multiple lines of text in the workshop box.

**Comment by jeremywalter** [comment]
Here is the e-mail link that people can mail to add themselves: CFDETraining+subscribe@CFDEpublic.groups.io
