### ISSUE TITLE
Contact Venues for Meeting

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#465]
All in Rockville area. 50 people. 2 breakouts.

50 people,  + 2 breakouts
AV
Rockville area
2 days
1-5 or 15-19th of November

7/19:
Marriott
Hilton
Cambria Rockville

**Comment by RLC-DCPPC** [comment]
Contacted both Marriott (Sheraton) and Hilton and got bids. Chose to move ahead with Hilton. 9/13/21: meeting switched to virtual.
