### ISSUE TITLE
Consider adding --from-history option to "conda list --export"

### ISSUE THREAD

**Issue by colbrydi** [nih-cfde/training-and-engagement#472]
I suggest that you consider including the --from-history argument when advising to export the conda list.  Although it will not reproduce the exact environment I have found that the argument makes for much easier to understand yml files.  Just a recommendation, I realize you also don't want to overburden the learner with too many details.

BTW. Thank you for this great tutorial.  I happen to be working on a similar one for python and having this as a reference will save me a lot of time!  I learned a lot.

**Comment by ctb** [comment]
thanks, Dirk!

I've used it a few times and it never did much for me, IIRC, but I think maybe I wasn't using it properly. We should try it again and include it if it slims down the list at all!

**Comment by marisalim** [comment]
thanks for this suggestion! adding on PR #475
