### ISSUE TITLE
setup GitHub action/workflow to check spelling

### ISSUE THREAD

**Issue by raynamharris** [nih-cfde/training-and-engagement#492]
Even thought spell check is part of our [reviewer checklist](https://github.com/nih-cfde/training-and-engagement/blob/dev/.github/workflows/comment_pr.yml), we still miss some typos (see #491). It would be good to setup a bot to do this. 

There are many options. Not sure which is best...

The dib-lab 2020 workflow paper uses [github workflow](https://github.com/dib-lab/2020-workflows-paper/blob/master/.github/workflows/manubot.yaml) with a custom [shell script](https://github.com/dib-lab/2020-workflows-paper/blob/master/ci/install-spellcheck.sh).

The [GitHub marketplace has a few options](https://github.com/marketplace?type=actions&query=spellcheck+), but I can't tell which will work nicely with the mkdocs build foo.

**Comment by raynamharris** [comment]
Update: I forked this repo and copied the files from https://github.com/check-spelling/spell-check-this to the `.github/` directory. It does trigger a spell check, but it is finding way too many words. I don't even know where all the words come form (see 
 https://github.com/raynamharris/training-and-engagement/pull/2). 

![Screen Shot 2021-12-12 at 5 02 36 PM](https://user-images.githubusercontent.com/7544197/145737384-92188200-fb50-4a36-8b46-e4abc3fbf58e.png)

![Screen Shot 2021-12-12 at 4 55 57 PM](https://user-images.githubusercontent.com/7544197/145737352-8658c8df-063a-414d-897c-02aa2e40d738.png)

Is there a way to tell the GitHub action only to spell check the files that were modified in the PR rather than all the files in the repo?

**Comment by s-canchi** [comment]
It looks like there is an actions list that can be used to manage the behavior of the workflow. This page lists all the available actions: https://github.com/check-spelling/spell-check-this/tree/main/.github/actions/spelling
The `only.txt` might be the one to add to indicate the spell check on only the git diff files.

**Comment by raynamharris** [comment]
gonna discard this. it can be revisited later
