### ISSUE TITLE
minor proofreading error

### ISSUE THREAD

**Issue by ishwarvh** [nih-cfde/training-and-engagement#495]
I was going through the notes and noticed that in section 6, the order in which the redirection commands are mentioned and described are incorrect. I think the redirect and append descriptions are flipped in the last sentence. Its a little bit confusing because you use "respectively" to connect the two sentences. 

"Much of the power of the UNIX command line comes from working with stdout output, and if you work with UNIX a lot, you'll see characters like the | (pipe), > (redirect), >> (append) thrown around. These are redirection commands that say, respectively, "send stdout to a new file", _"append stdout to an existing file"_, and "_send stdout from one program to another program's stdin_." "

**Comment by raynamharris** [comment]
Hi @ishwarvh. Thank you so much for catching this. I changed the order of the first sentence a while back but didn't change the second sentence. I have correct the error in all the places. Thank you :)
