### ISSUE TITLE
Initial intake/concept Researcher interviews

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#5]
Milestone for https://github.com/nih-cfde/cfde-deriva/issues/9

- [ ] Confirm IG date/time openings
- [ ] Determine number interviewees
- [ ] Identify end users
- [ ] Book X interviewees

**Comment by jeremywalter** [comment]
Any more to do here?

**Comment by ACharbonneau** [comment]
Yup. All the things in the list :)

**Comment by jeremywalter** [comment]
Ah, so this is the next round and who decides when that happens? IG?

**Comment by ACharbonneau** [comment]
Some combination of me, IG, Carl and Owen I think.
