### ISSUE TITLE
Tool to move data to Cavatica

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#506]
Assuming the issues with viewing data in Cavatica are fixed by then, we will want to use the CLI during our second hackathon to push data into Cavatica.  This would be in early to mid April 2022.

**Comment by ACharbonneau** [comment]
If you think it would be useful Mike, we could have you attend during the time we use it so you can see what people do and don't like to make any changes you want before the deliverable is actually due in end of april. I guess it depends what our date ends up being whether there'd be time for updates in that window.

**Comment by RLC-DCPPC** [comment]
@mikedarcy , are we still doing this?

**Comment by mikedarcy** [comment]
This has been superseded by the implementation in described in https://github.com/nih-cfde/cfde-deriva/issues/334.
