### ISSUE TITLE
Set up an orientation meeting 

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#52]
We need to set up a meeting for CFDE-CC to present to our new oversight committee. @kutkatl is getting me the list of people who would attend. @nih-cfde/coordinators We need to:

- [ ] Come up with an agenda (with @owhite)
- [x] pick a time
- [ ] invites and meeting setup

**Comment by josesanchez1815** [comment]
@ACharbonneau  what is the goal of this meeting? What kind of agenda are we moving towards?

**Comment by ACharbonneau** [comment]
Going to have @josesanchez1815 handle scheduling of this one. Just waiting on confirmed invite list.

**Comment by owhite** [comment]
Oversight committee agenda:

**Purpose of meeting**

- Summary, timeline, findings from outreach activities
- Project management components
- Use-cases, requirements
- Federation approach
- CFDE portal / dashboard review
- Coordination with GA4GH interoperation

**Comment by josesanchez1815** [comment]
# Orientation Meeting
**_June 12th, 2020 8AM - 11AM_**
Owen White 
Titus Brown
Ari Khan
Martin Lindquist
James Carson

**Comment by ACharbonneau** [comment]
@josesanchez1815 Can you find out when Owen is available next week for this meeting. It's best to ask Danay. Ask for 1-2 hour blocks he has open.

**Comment by josesanchez1815** [comment]
Just sent an e-mail to Danay. Waiting for her response.

**Comment by ACharbonneau** [comment]
@josesanchez1815 Please 
- check with Titus on whether he'd like to attend this meeting
- Then, assuming he does, when you get the times from Danay, cross check them and make a list of the ones they can both do.
- Please check with me after that, so I can make sure the suggested times fit my schedule
- Once you have that final list, you'll send them to NIH.

Your contact at NIH who needs the list of times is Micheal Ojiere, I just sent you his contact info.

**Comment by josesanchez1815** [comment]
# Meeting Time 
June 18th 11-12th EST
@ACharbonneau @owhite @ctb

**Comment by ACharbonneau** [comment]
NIH has taken over planning this
