### ISSUE TITLE
Get new content actually rendering in website

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#53]
Re: [this PR](https://github.com/nih-cfde/training-and-engagement/pull/51) 

When people are checking PRs for this (and any other website repo) we need to be sure we're checking not just the changes, but whether they are properly formatted for the website. In this case, the new content isn't rendering, and needs to get fixed

**Comment by abhijna** [comment]
I'm working on multiple aspects of this website. They will all get fixed in the same PR.
