### ISSUE TITLE
Outreach: Hackathons to support Knowledge Base content

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/training-and-engagement#536]
The Knowledge Base should be a resource that reflects the needs and questions of the scientific community. While the Coordination Center will create basic content in our Knowledge Base deliverable, incorporating content from researchers who are interested in a given resource will add richness and usefulness beyond what the Coordination Center can provide. We will facilitate the creation of richer resources by holding hackathons where DCC staff, R03 awardees, and/or researchers with an interest in Common Fund data can help to brainstorm or generate new content. We expect that the DCCs will be interested in using this registry as a display for knowledge graph information. Deliverable: two hackathons, exact dates to be determined by participants preference. One by 7/30, the second by 8/30.

**Comment by raynamharris** [comment]
Website: https://github.com/nih-cfde/2022-content-generation-sprints
Intent to participate and available form https://forms.gle/zppvKfF5NQPXj4sr9
