### ISSUE TITLE
UNIX lesson page is broken

### ISSUE THREAD

**Issue by jessicalumian** [nih-cfde/training-and-engagement#539]
The UNIX page is rendered poorly: https://training.nih-cfde.org/en/latest/General-Tools/UNIX.html

I'm sure this will be fixed in the June 15 release (#532), but if there's a quick fix before then it would be nice to fix it.

**Comment by raynamharris** [comment]
i know. there are no quick fixes. it is because the index page is linking to a page that does not exist. i updated the index months ago when i was thinking about adding the unix lesson but did not add it. i missed this. the link will work in 10 days.
