### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by raynamharris** [nih-cfde/training-and-engagement#551]
the release notes points to a non-existent index.md page in the iHMP folder. 

so, to get to this tutorial you have to got to https://training.nih-cfde.org/en/latest/Common-Fund-Tools/CFDE-Portal/iHMP/find-export/

**Comment by raynamharris** [comment]
alternatively, i could point to the cfde portal section one level up.

https://training.nih-cfde.org/en/latest/Common-Fund-Tools/CFDE-Portal/

**Comment by jeremywalter** [comment]
sounds good (approved relevant PR) https://github.com/nih-cfde/training-and-engagement/pull/552

**Comment by raynamharris** [comment]
hmm. i closed this too soon. can't merge stable into dev now :(
![Screen Shot 2022-06-30 at 11 56 00 AM](https://user-images.githubusercontent.com/7544197/176756498-b4d2af02-73bb-4235-b9a6-07dba7e955d5.png)
