### ISSUE TITLE
Create DCC Communications Log

### ISSUE THREAD

**Issue by RebeccaBoyles** [nih-cfde/training-and-engagement#56]
Create log of contacts and activites here: https://docs.google.com/spreadsheets/d/1M6iLKBZYxawpE4n8pITFOgiQURlY8r9X5yTFqlpdUd4/edit?usp=drive_web&ouid=108192684741573654994

**Comment by dcfcjcheadle** [comment]
Documented initial contact on **29 MAY 2020** and added additional points of contact from the LINCS team.
