### ISSUE TITLE
Discuss questions/Interview plans for Portal Researcher interface tests

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/training-and-engagement#6]
Milestone for https://github.com/nih-cfde/cfde-deriva/issues/9

- [ ] Need to set up meeting with Interface Guru after #5

**Comment by ACharbonneau** [comment]
Had initial meeting, waiting on IG to see finalized questions. Meeting for 4/29 was cancelled, not yet rescheduled

**Comment by jeremywalter** [comment]
Cancelled indefinitely
